### ISSUE TITLE
timeout set too low in ./occ

### ISSUE THREAD

**Issue by debian-user-france1** [marcelklehr/recognize#100]
The classifier doesn't work anymore

A node process starts as it should but shortly after it reports 'classifier timed out'

I used occ to run the classifier manually

**Comment by debian-user-france1** [comment]
recently an automatic run classified some (many)
Did the model update?

**Comment by debian-user-france1** [comment]
It's a very little chance to work. There's no Iasue with RAM (3GB free and 11GB swap, includes zram of min. 2GB)

I don't know where the logs should be - it's made very poor (no output..)

**Comment by debian-user-france1** [comment]
Hmmm wait...

It's in red: Failed to classify images
And in white: Classifier processes timeout

Actually, there's almost 1GB RAM free when I see a node process but it only uses 6% CPU and there's a swappiness process using almost same % CPU

**Comment by debian-user-france1** [comment]
Please remove duplicate and reopen

I don't have the RAM issue anymore

**Comment by bonswouar** [comment]
Ok the ram problem might be unrelated to your initial problem.
Although you said earlier it did run, did it work then? What have you changed since?
Is your error still `Cannot find module 'fs/promises'`? Did you change node's path in the config?

**Comment by debian-user-france1** [comment]
It seems to work but then the process dies because it's parrent (the ./occ command) decides to stop because of 'timeout'

**Comment by bonswouar** [comment]
I fear timeout could mean anything, what's the output exactly, the same as your screenshot (`Cannot find module 'fs/promises'`)?

**Comment by debian-user-france1** [comment]
This is what happens when I just run it with occ: https://cloud.privacyy.ch/index.php/s/DE4ZSRx67k2BnXy

**Comment by debian-user-france1** [comment]
> Timeout is set to 10 seconds per image (50 in pure JS mode), it shouldn't take more. The warning may indicates there is a memory problem and thus it probably takes more time than it should

No on my system it has to put serveral things to RAM like some Apache cache files so it takes more for the 1. picture than for the others (I guess lol)

**Comment by debian-user-france1** [comment]
Can you give me the path of this file so I can mess around?

**Comment by debian-user-france1** [comment]
I ask for duplicate-sign removal for the issue
Finally, it's proven that there's no other issue with the same problem

**Comment by marcelklehr** [comment]
> Seeing those issues maybe we should add a command option to have a verbose output when running the classifier for debugging purpose, what do you think @marcelklehr ?

Yeah, completely moving the debug output to the nextcloud log was a bad move it seems. I'm not sure how best to have debug output at both ends and keep the code DRY.

> I don't know what's the best way for that, we could make it configurable but that's a bit tricky for any user to know which timeout value he'd want.

I'm happy to increase the timeout, even if that means it's gonna be much higher. It was only ever meant as a way to avoid waiting on the process forever.

**Comment by bonswouar** [comment]
Alright, if a high timeout value isn't a problem let's go for that!
