### ISSUE TITLE
Unable install in NextcloudPI

### ISSUE THREAD

**Issue by gyb001** [marcelklehr/recognize#109]
When i click to install button this show: 
Could not extract app recognize: Out-of-path file extraction {/media/myCloudDrive/ncdata/tmp/oc_tmp_ZPpfzN-folder/recognize/node_modules/sass-loader/node_modules/.bin/semver --> ../semver/bin/semver.js}

Latest NextcloudPi
Pi4 8gb.

**Comment by spicemint** [comment]
I'm a little unclear if recognize is supposed to work on a pi or not, i got it installed but it does not seem to work at all, is it working on 32 bit architecture?
