### ISSUE TITLE
Mass periodical external Storage ALL files download

### ISSUE THREAD

**Issue by GAS85** [marcelklehr/recognize#116]
**Describe the bug**
As per https://github.com/nextcloud/server/issues/29744

Since last update a lot of data downloaded (around 5 MB/s for 10 Min = around 3 GB downloaded) from external storages.
With `tcptrack` find out that all traffic goes to only 1 external share - [Magenta Cloud](https://www.magentacloud.de/).
Files were not changed since 2017 and correctly tagged, but still downloaded to be analyzed each 10-20 min.

**To Reproduce**

1. Use external Storage via WebDav
2. Upgrade to the latest Recognize App
3. From some point periodical mass download will appear:
![grafik](https://user-images.githubusercontent.com/6813635/142160003-e647c847-cfb8-417a-abb3-53e867ad55ac.png)
4. Check `tmp` Folder and it is full of files from the external storage (was checked by download and open few of tmp files):
```bash
ls -la /tmp/oc_*
-rw------- 1 www-data www-data         0 Nov 17 09:19 /tmp/oc_tmp_0ABNip
-rw------- 1 www-data www-data   6519718 Nov 17 09:19 /tmp/oc_tmp_0ABNip-.JPG
-rw------- 1 www-data www-data         0 Nov 17 09:17 /tmp/oc_tmp_0BASfm
-rw------- 1 www-data www-data      4757 Nov 17 09:17 /tmp/oc_tmp_0BASfm-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_0JPaKn
-rw------- 1 www-data www-data     14135 Nov 17 09:16 /tmp/oc_tmp_0JPaKn-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_0Ytsul
-rw------- 1 www-data www-data    400761 Nov 17 09:16 /tmp/oc_tmp_0Ytsul-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_0iJTEp
-rw------- 1 www-data www-data      8528 Nov 17 09:16 /tmp/oc_tmp_0iJTEp-.png
-rw------- 1 www-data www-data         0 Nov 17 09:17 /tmp/oc_tmp_0xJSqp
-rw------- 1 www-data www-data      3928 Nov 17 09:17 /tmp/oc_tmp_0xJSqp-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_11tZKo
-rw------- 1 www-data www-data     37630 Nov 17 09:16 /tmp/oc_tmp_11tZKo-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_1ML1Nl
-rw------- 1 www-data www-data     33559 Nov 17 09:16 /tmp/oc_tmp_1ML1Nl-.png
-rw------- 1 www-data www-data    139075 Nov 17 09:16 /tmp/oc_tmp_1UwNMo
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_1VtGYl
-rw------- 1 www-data www-data      7168 Nov 17 09:16 /tmp/oc_tmp_1VtGYl-.xls
-rw------- 1 www-data www-data         0 Nov 17 09:17 /tmp/oc_tmp_1YnGln
-rw------- 1 www-data www-data      6147 Nov 17 09:17 /tmp/oc_tmp_1YnGln-.png
-rw------- 1 www-data www-data         0 Nov 17 09:16 /tmp/oc_tmp_1dvkdo
-rw------- 1 www-data www-data   3394241 Nov 17 09:16 /tmp/oc_tmp_1dvkdo-.pdf
-rw------- 1 www-data www-data         0 Nov 17 09:18 /tmp/oc_tmp_2DeKSp
-rw------- 1 www-data www-data  48512299 Nov 17 09:18 /tmp/oc_tmp_2DeKSp-.mp4
....
```
5. Seems a lot of data downloaded (around 5 MB/s for 10 Min = around 3 GB downloaded). External Storage is around 3 GB big.
6. Check files in external Storage - all are tagged with `Tagged by recognize` and unmodified since years:
![grafik](https://user-images.githubusercontent.com/6813635/142202162-01f74dbf-071d-41ea-93bd-f47da018370f.png)
7. Amount of recognized files will remain the same. And Cron Job will use whole time of it --> https://github.com/nextcloud/server/issues/29744#issuecomment-971435490
 
**Expected behavior**
Unchanged files should not be downloaded again and again for analyses.

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: object detection

**Server (please complete the following information):**
 - Nextcloud: 21.0.7
 - OS: Ubuntu 20.04
 - RAM: 16GB
 - Processor Architecture Zen 3 (AMD Ryzen 3 3200G)

**Comment by bonswouar** [comment]
@GAS85 Thank you for the clean issue, and sorry for the late reply!

Do you know if it's something new (related to nc update)?
We don't do any processing on the files before checking it's tags, and if it's got recognized already it skips it.

Basically I see only `$folder->getDirectoryListing()` _(checking directory file list)_ or, more likely, `$this->objectMapper->haveTag([$node->getId()], ..)` __(checking if recognized tag is present)__ that could be the culprit, but they're not supposed to download any file afaik?

I hope it's not mandatory to retrieve the file from external storage to be able to get its tags, I actually don't know much about how tags are handled in Nextcloud. Any thought @marcelklehr ?

**Comment by bonswouar** [comment]
I've just checked, php `haveTag` method doesn't retrieve the file but only use the database: https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/SystemTag/SystemTagObjectMapper.php#L212
Could be a bad implementation/usage of `getDirectoryListing` using webdav then, but I don't see why it would: https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Files/Storage/DAV.php#L214

That's definitely weird, I'll need to do some testing; meanwhile I'm open to suggestions

**Comment by GAS85** [comment]
Could be that this is something wrong with Nextcloud itself? Seems not only this applications affected. As per comment, there is also all files mass download to generate new previews from the SMB https://help.nextcloud.com/t/lots-of-sabre-errors-nc-to-slow-to-use/128311/7?u=gas85

**Comment by bonswouar** [comment]
>  I check update logs and on 09.10.2021 I perform update from 20.0.12 to 21.0.4, shortly after this periodical downloads appears.

Well the mystery deepens. Apparently there are no differences between 20.0.12 and 21.0.4 in DAV.php, even "sabre/dav"  library hasn't been updated.

**Comment by marcelklehr** [comment]
Can you verify whether this continues to happen when deactivating recognize?

**Comment by GAS85** [comment]
Periodical - yes it is triggered by this app.
Mass download - no, seems Nextcloud changed something and even simple UI to external storage now doing the same as per nextcloud/server/issues/30262 and nextcloud/server/issues/30282

**Comment by marcelklehr** [comment]
@GAS85 I see. In that case I'll close this for now. Feel free to shout here or open a new issue if this app turns out to be the problem after all.

**Comment by GAS85** [comment]
I find that `PROPFOUND` that everybody are using to get File information such as TAGs etc. Causing files download, this is a root cause of spikes: https://github.com/nextcloud/server/issues/30262#issuecomment-1010781345
