### ISSUE TITLE
Updating to 1.7.0 ends up in maintainance mode 

### ISSUE THREAD

**Issue by Emporea** [marcelklehr/recognize#120]
NC: 22.2.3
Version before upgrade: 1.6.10
Version after upgrade: 1.7.0

It took a long time ~10 min to upgrade the app via web interface until an error happend.
Nextcloud went into maintainance mode for about 5 mins.

I guess there was just a lot of computation while upgrading to 1.7.0, is this intended?

No error was produced in nextcloud.log / proxy / etc.

The app seems to be working tho and it successfully upgraded to 1.7.0, but it took about 15 minutes.

This might be a nonsense issue. Sorry.

**Comment by Emporea** [comment]
about 1500 processed files and 1500 unrecognized files after hitting
`occ recognize:classify-audio`
but there seems to be an error with the taggs. 

Every track has these taggs, and nothing shows up in the Audioplayer app.
![image](https://user-images.githubusercontent.com/21969523/146089468-fe85ff78-1752-4e15-beb3-eb774d768319.png)

**Comment by marcelklehr** [comment]
> nothing shows up in the Audioplayer app

The audioplayer app should at least show the Unrecognized tag after selecting the tags view. :/

> about 1500 processed files and 1500 unrecognized files

Can you check the nextcloud log for errors?

**Comment by marcelklehr** [comment]
> The app seems to be working tho and it successfully upgraded to 1.7.0, but it took about 15 minutes.

Installation can indeed take some time as it's a large bundle and requires some setup as well.

**Comment by Emporea** [comment]
> > nothing shows up in the Audioplayer app
> 
> The audioplayer app should at least show the Unrecognized tag after selecting the tags view. :/
> 
> > about 1500 processed files and 1500 unrecognized files
> 
> Can you check the nextcloud log for errors?

The recognize app itself seems to produce no errors, even tho I can't see any taggs created that represents a music genre. Only Images etc.


But the Audioplayer App has a huge error output. About 100 times per second this error pops up, when trying to open Tags in Audioplayer.
```
[PHP] Error: Undefined array key "count" at /var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php#79

GET /apps/audioplayer/getcategoryitems?category=Tags
from xxxx by emporea at 2021-12-15T13:09:22+00:00


{"reqId":"704JpSVkmN3WLg0OgegA","level":3,"time":"2021-12-15T13:09:22+00:00","remoteAddr":"xxxx","user":"emporea","app":"PHP","method":"GET","url":"/apps/audioplayer/getcategoryitems?category=Tags","message":"Undefined array key \"count\" at /var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php#79","userAgent":"Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0","version":"22.2.3.0","exception":{"Exception":"Error","Message":"Undefined array key \"count\" at /var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php#79","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php","line":79,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Undefined array key \"count\"","/var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php",79]},{"file":"/var/www/html/custom_apps/audioplayer/lib/Categories/Tag.php","line":50,"function":"getTrackCount","class":"OCA\\audioplayer\\Categories\\Tag","type":"->","args":["115"]},{"file":"/var/www/html/custom_apps/audioplayer/lib/Controller/CategoryController.php","line":160,"function":"getCategoryItems","class":"OCA\\audioplayer\\Categories\\Tag","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"getCategoryItems","class":"OCA\\audioplayer\\Controller\\CategoryController","type":"->","args":["Tags"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\audioplayer\\Controller\\CategoryController"},"getCategoryItems"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\audioplayer\\Controller\\CategoryController"},"getCategoryItems"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\audioplayer\\Controller\\CategoryController","getCategoryItems",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"audioplayer.category.getCategoryItems"}]},{"file":"/var/www/html/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/audioplayer/getcategoryitems"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61b9f555e07dd"}
```


Should I open an issue in the audioplayer app? But for you it worked while developing 1.7.0?
And we are both talking about the [rello/audioplayer](https://github.com/Rello/audioplayer) app ?

**Comment by marcelklehr** [comment]
> But for you it worked while developing 1.7.0?

Ah, I had to [patch](https://github.com/Rello/audioplayer/pull/554) the audioplayer app for it to work, it seems @rello hasn't published a release with that patch, yet.

**Comment by Emporea** [comment]
Ah okey. I am glad to hear that. :)

But besides the audioplayer app shouldnt be music tags also be visible through the Files/Tags section? But there are only tags for images as far as I can tell.

I don't know if my music is just too abnormal for musicnn to recognize anything :D, 
but like I already said

> about 1500 processed files

They need to be somewhere?

**Comment by marcelklehr** [comment]
> too abnormal for musicnn to recognize anything

I'd phrase it more like "The model wasn't exposed to your music, yet." But it is possible, do you mind sharing the genre (here or in a private mail)?

> They need to be somewhere?

Processed just means they went through the classifier. If number of processed == number of unrecognized, then the app wasn't able to reliably classify the files in question.
