### ISSUE TITLE
ValueError: Path cannot be empty in /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php:93

### ISSUE THREAD

**Issue by gmeks** [marcelklehr/recognize#121]
**Describe the bug**
Crashing when running command classify-images

**To Reproduce**
Run command in shell.
Likely have a profile that has a bad photo in their profile.

**Expected behavior**
Not crash

**Recognize (please complete the following information):**
 - JS-only mode:no 
 - Enabled modes: object detection, face recognition

**Server (please complete the following information):**
 - Nextcloud: 22.2.3
 - RAM: 8GB
 - Processor Architecture x86

**Additional context**

My suspesion from checking out the code ( I dont realy know php), is that i dont see null or badformat handling when getting the format from the contacts.
Perhaps it should check that its not null, and some very basic format check? ( Its a base64 image i belive)

sudo -u www-data php /var/www/nextcloud/occ recognize:classify-images
Classifying photos of user eks
An unhandled exception has been thrown:
```
ValueError: Path cannot be empty in /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php:93
Stack trace:
#0 /var/www/nextcloud/apps/recognize/lib/Service/ReferenceFacesFinderService.php(93): file_get_contents()
#1 /var/www/nextcloud/apps/recognize/lib/Command/ClassifyImages.php(92): OCA\Recognize\Service\ReferenceFacesFinderService->findReferenceFacesForUser()
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Recognize\Command\ClassifyImages->execute()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('...')

```

Following changes seems to have stopped the issue, but should likely be made better.
![bilde](https://user-images.githubusercontent.com/4104522/146391661-c97d9195-6662-46f0-bc20-d8c94fbd99c4.png)

**Comment by bonswouar** [comment]
Thanks for the report!
I've also noticed some errors here with invalid (but not null) photos, should be fixed soon

**Comment by gmeks** [comment]
It should not stop, thats my reading to. As its inside a try catch
