### ISSUE TITLE
Processed files: 0 Unrecognized files: 0, does this app do anything?

### ISSUE THREAD

**Issue by aegisgfx** [marcelklehr/recognize#124]
So does this app do anything? I have NC 22.2, php 7.4, lots of ram. Its just sits there doing nothing. I have setup the setting/recognize tab for object and face recognition and nothing happens. I tried running the command occ recognize:classify-images manual, nothing happens, it never stops, it never errors, I just get nothing.

**Comment by marcelklehr** [comment]
Mmh. That's curious. Can you check the nextcloud log with full log verbosity?

**Comment by aegisgfx** [comment]
I hope this helps, doesnt tell me much 
Line 13958: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Pictures/iPhone/Pictures/tatay's day/F9D9B783-2DA9-4A29-AC43-84FB0EE132B8.JPG","userAgent":"--","version":"22.2.0.2"}
	Line 13959: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":2,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifying photos of user imee","userAgent":"--","version":"22.2.0.2"}
	Line 13960: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifying array (\n  0 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Birdie.jpg',\n  1 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Frog.jpg',\n  2 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Gorilla.jpg',\n  3 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Library.jpg',\n  4 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Nextcloud community.jpg',\n  5 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Steps.jpg',\n  6 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Toucan.jpg',\n  7 => '/media/3TB/www/nextcloud/data/imee/files/Photos/Vineyard.jpg',\n  8 => '/media/3TB/pictures/imee/2017/20171230_235936.jpg',\n  9 => '/media/3TB/pictures/imee/2017/20171231_000000.jpg',\n  10 => '/media/3TB/pictures/imee/2017/20171231_181322.jpg',\n  11 => '/media/3TB/pictures/imee/2017/20171231_181426.jpg',\n  12 => '/media/3TB/pictures/imee/2017/20171231_191726.jpg',\n  13 => '/media/3TB/pictures/imee/2017/20171231_191731.jpg',\n  14 => '/media/3TB/pictures/imee/2017/20171231_191745.jpg',\n  15 => '/media/3TB/pictures/imee/2017/20171231_191759.jpg',\n  16 => '/media/3TB/pictures/imee/2017/20171231_191809.jpg',\n  17 => '/media/3TB/pictures/imee/2017/20171231_191904.jpg',\n  18 => '/media/3TB/pictures/imee/2017/20171231_191906.jpg',\n  19 => '/media/3TB/pictures/imee/2017/20171231_191908.jpg',\n  20 => '/media/3TB/pictures/imee/2018/20180103_220802.jpg',\n  21 => '/media/3TB/pictures/imee/2018/20180103_220856.jpg',\n  22 => '/media/3TB/pictures/imee/2018/20180103_220858.jpg',\n  23 => '/media/3TB/pictures/imee/2018/20180103_221411.jpg',\n  24 => '/media/3TB/pictures/imee/2018/20180103_221717.jpg',\n  25 => '/media/3TB/pictures/imee/2018/20180104_214044.jpg',\n  26 => '/media/3TB/pictures/imee/2018/20180104_214504.jpg',\n  27 => '/media/3TB/pictures/imee/2018/20180104_214632.jpg',\n  28 => '/media/3TB/pictures/imee/2018 ...
	Line 13961: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Running array (\n  0 => '/media/3TB/www/nextcloud/apps/recognize/bin//node',\n  1 => '/media/3TB/www/nextcloud/apps/recognize/src/classifier_imagenet.js',\n  2 => '-',\n)","userAgent":"--","version":"22.2.0.2"}
	Line 13961: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Running array (\n  0 => '/media/3TB/www/nextcloud/apps/recognize/bin//node',\n  1 => '/media/3TB/www/nextcloud/apps/recognize/src/classifier_imagenet.js',\n  2 => '-',\n)","userAgent":"--","version":"22.2.0.2"}
	Line 13961: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Running array (\n  0 => '/media/3TB/www/nextcloud/apps/recognize/bin//node',\n  1 => '/media/3TB/www/nextcloud/apps/recognize/src/classifier_imagenet.js',\n  2 => '-',\n)","userAgent":"--","version":"22.2.0.2"}
	Line 13964: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":2,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: ","userAgent":"--","version":"22.2.0.2"}
	Line 13965: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":2,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process errored","userAgent":"--","version":"22.2.0.2"}
	Line 13966: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":2,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"22.2.0.2"}
	Line 13967: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Recognize\\BackgroundJobs\\ClassifyImagesJob job with ID 13603 in 21 seconds","userAgent":"--","version":"22.2.0.2"}
	Line 13968: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Recognize\\BackgroundJobs\\ClassifyAudioJob job with ID 13604","userAgent":"--","version":"22.2.0.2"}
	Line 13969: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching files","userAgent":"--","version":"22.2.0.2"}
	Line 13970: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching files/Documents","userAgent":"--","version":"22.2.0.2"}
	Line 13971: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching files/Music","userAgent":"--","version":"22.2.0.2"}
	Line 13972: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/3189710287847414911.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13973: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/4 In the Morning.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13974: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/A Thousand Years.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13975: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Alone Again (feat. P. Reign).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13976: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Blank Space.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13977: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Blurred Lines (feat. T.I. & Pharrell).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13978: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/California (There Is No End to Love).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13979: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Cedarwood Road.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13980: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Close to You - Half a Minute.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13981: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Collide (Original).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13982: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Everybody Dance Now (Rock This Party) [Ronnie Maze Club Mix].m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13983: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Girl from Ipanema.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13984: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Give Me One Reason.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13985: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Glory of Love (Theme from the Karate Kid, Pt. II).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13986: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/God Gave Me You (Single Version).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13987: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Heart Attack.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13988: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Holy Grail (feat. Justin Timberlake).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13989: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/I Melt With You.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13990: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/I'll Be Missing You.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13991: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/If You Leave Me Now (New Version).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13992: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Invisible War.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13993: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Iris (Hold Me Close).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13994: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Kiss Me.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13995: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Let It Go.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13996: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Life Is a Highway.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13997: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Marvin Gaye (feat. Meghan Trainor).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13998: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Mirrors.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 13999: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/One Call Away.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14000: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Points of View.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14001: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Royals (Remix).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14002: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Set Fire to the Rain.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14003: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Stay With Me.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14004: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Tattooed On My Mind.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14005: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Titanium (feat. Sia).m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14006: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Try Sleeping with a Broken Heart.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14007: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/Turning Tables.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14008: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/We Can't Stop.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14009: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/What Are You Waiting For_.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14010: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/When We Were Young.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14011: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Found /imee/files/Music/You'll Be In My Heart.m4a","userAgent":"--","version":"22.2.0.2"}
	Line 14012: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching files/Photos","userAgent":"--","version":"22.2.0.2"}
	Line 14013: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching files/Templates","userAgent":"--","version":"22.2.0.2"}
	Line 14014: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching ","userAgent":"--","version":"22.2.0.2"}
	Line 14015: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2017","userAgent":"--","version":"22.2.0.2"}
	Line 14016: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2018","userAgent":"--","version":"22.2.0.2"}
	Line 14017: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:31+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2018/banff 2018","userAgent":"--","version":"22.2.0.2"}
	Line 14018: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:31+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2019","userAgent":"--","version":"22.2.0.2"}
	Line 14019: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:32+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2020","userAgent":"--","version":"22.2.0.2"}
	Line 14022: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:34+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2020/cache","userAgent":"--","version":"22.2.0.2"}
	Line 14023: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:34+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2020/cache/latest","userAgent":"--","version":"22.2.0.2"}
	Line 14024: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:34+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching 2021","userAgent":"--","version":"22.2.0.2"}
	Line 14025: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:36+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching Facebook","userAgent":"--","version":"22.2.0.2"}
	Line 14026: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:36+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching Vids","userAgent":"--","version":"22.2.0.2"}
	Line 14027: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching cache","userAgent":"--","version":"22.2.0.2"}
	Line 14028: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching cache/latest","userAgent":"--","version":"22.2.0.2"}
	Line 14029: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching iPhone","userAgent":"--","version":"22.2.0.2"}
	Line 14030: {"reqId":"wBYVd7LDh1ZQaIq9qvE9","level":0,"time":"2021-12-21T19:00:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Searching iPhone/Pictures","userAgent":"--","version":"22.2.0.2"}

**Comment by marcelklehr** [comment]
It looks like it fails to execute the node.js binary. What's your processor architecture? Does your system have glibc?

**Comment by aegisgfx** [comment]
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.4) 2.31

**Comment by aegisgfx** [comment]
Intel(R) Core(TM)2 Quad CPU Q8300 @ 2.50GHz, 4 cores

**Comment by marcelklehr** [comment]
Looks good at first glance. It might just take a long time, for technical reasons the command didn't log anything to the console before v1.8.x -- with the latest version you should get some status output, though. Let me know what happens after updating :)

**Comment by aegisgfx** [comment]
Ok now I get a specific error:

Running array (
  0 => '/media/3TB/www/nextcloud/apps/recognize/bin//node',
  1 => '/media/3TB/www/nextcloud/apps/recognize/src/classifier_musicnn.js',
  2 => '-',
)
Classifier process output:
Failed to classify audio
Classifier process error

**Comment by marcelklehr** [comment]
Mh. Can you try to run the classifier manually?

```bash
$ /media/3TB/www/nextcloud/apps/recognize/bin//node /media/3TB/www/nextcloud/apps/recognize/src/classifier_musicnn.js <path to some music file>
```

**Comment by marcelklehr** [comment]
I just researched your CPU a bit and afaict it doesn't support AVX. That means you can either run in JS mode (which is still very slow in v1.8.x, but will get faster with the next release), or you can build libtensorflow from source for your architecture.
