### ISSUE TITLE
JS-only mode in background job blocks the whole cron task

### ISSUE THREAD

**Issue by troyliu0105** [marcelklehr/recognize#125]
**Describe the bug**
recognize process will block cron task when there's a lot images on the NC server.

**To Reproduce**
I ran nextcloud docker image on TrueNAS scale with k3s. I noticed that `Background jobs` shows `Something seems wrong...`.

First. I ran `docker exec -ti --user www-data nc-container php -f /var/www/html/cron.php` to manual execute cron job. It just hangs forever...
and `top` shows `node` recognize process use 100% cpu:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/5518286/147763513-a07b0e8a-0c9a-40ad-b0c5-c567f5c85e43.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/5518286/147764288-37ba4d7c-5a30-4e5f-8514-8baa7b992057.png">

**Expected behavior**
I think that recognition app should run with relative low resource usage and continuous running to silently detect images (just like iOS device will do this job when device is connected with charger and not be used). otherwise the other cron jobs can't be executed forever.

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: object detection, face recognition

**Server (please complete the following information):**
 - Nextcloud: 22.2.3
 - OS: TrueNAS Scale (Debian)
 - RAM: 24GB
 - Processor Architecture: x86

**Comment by marcelklehr** [comment]
Hey @troyliu0105 

Thank you for reporting this. Since js-only mode is significantly slower, we should definitely reduce the amount of images processed per 10 minutes accordingly, to avoid overloading the server.
