### ISSUE TITLE
Groupfolders cause Failed to classify Images

### ISSUE THREAD

**Issue by pancan21** [marcelklehr/recognize#126]
**Describe the bug**
After running successfully for all users without access to a groupfolder the classification exits with the error:

Failed to classify images
File with id "XXXXX" has not been found.

The fileid corresponds to the groupfolder in the oc_filecache database.

**To Reproduce**
1. Download Groupfolder app
2. Create new Groupfolder and grant access to one of the users
3. Run 'occ recognize:classify-images' command

**Expected behavior**
I would expect it to recognize and follow the path __groupfolders/<groupfolder id> given in the oc_filecache db and add tags to the images inside as for any other folder.

**Recognize:**
 - JS-only mode: No
 - Enabled modes: object detection

**Server:**
 - Nextcloud: 22.2.3
 - OS: Ubuntu 18.01 LTS
 - RAM: 32GB
 - Processor Architecture x84

**Comment by bonswouar** [comment]
@pancan21 I don't know this Groupfolder app, but afaik we use pretty standard methods from `OCC/Files` library to recursively parse folders.
Are you sure it's not a Groupfolder issue?
If so, could you provide the actual error logs?

**Comment by pancan21** [comment]
Thanks for your hint, took me some time to dig deeper.
It was actually a broken folder link that was somehow not removed, by `occ files:scan --all`
After manual removal, everything was working fine again.
Sorry for the wrong flag!
