### ISSUE TITLE
Feature Request Reset Tags

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [marcelklehr/recognize#127]
Hi!
It would be very nice if it would be possible to reset / delete all created tags from the files with the command line and don't get activities for every deletion.
Alternative if would be nice if old pictures which was already taged will be automatically from time to time revisited and reclassified.
best regards

**Comment by bonswouar** [comment]
> It would be very nice if it would be possible to reset / delete all created tags from the files with the command line

This can already be done from the UI, why not use this? I don't mind adding more commands, but I'm not sure this is a very good practice with Nextcloud apps

>  and don't get activities for every deletion.

I tend to agree with that part (even if run from the UI), although not sure this is recommended (?)

>  Alternative if would be nice if old pictures which was already taged will be automatically from time to time revisited and reclassified.

I believe this would be quite useless if no update of the model has been done meanwhile. But maybe we could just add a boolean or something for updates with new/updated models (and reset that boolean when scan has been done)?

@marcelklehr feel free to complete

**Comment by MrLoverLoverMMMM** [comment]
OkThe boolean soubds fine that if there is a new model it revisits photos :)
-------- Ursprüngliche Nachricht --------Von: bonswouar ***@***.***> Datum: 17.01.22  18:20  (GMT+01:00) An: marcelklehr/recognize ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [marcelklehr/recognize] Feature Request Reset Tags (Issue #127) 

It would be very nice if it would be possible to reset / delete all created tags from the files with the command line

This can already be done from the UI, why not use this? I don't mind adding more commands, but I'm not sure this is a very good practice with Nextcloud apps

and don't get activities for every deletion.

I tend to agree with that part (even if run from the UI), although not sure this is recommended (?)

Alternative if would be nice if old pictures which was already taged will be automatically from time to time revisited and reclassified.

I believe this would be quite useless if no update of the model has been done meanwhile. But maybe we could just add a boolean or something for updates with new/updated models (and reset that boolean when scan has been done)?
@marcelklehr feel free to complete

**Comment by marcelklehr** [comment]
> It would be very nice if it would be possible to reset / delete all created tags from the files with the command line

I'm happy to add those as commands if this is useful.

> don't get activities for every deletion.

That's probably not possible :/

> But maybe we could just add a boolean or something for updates with new/updated models (and reset that boolean when scan has been done)?

That's a good idea. Can you put that in a new issue?
