### ISSUE TITLE
Feature Request: Possibility to set the maximum amount of ram the tool can use when running it from the command line.

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [marcelklehr/recognize#128]
Possibility to set the maximum amount of ram the tool can use when running it from the command line.
At my setup the classification eats after 3-4h time 100 GB RAM if I run it via the shell.
A limit in the shell parameter would be perfect for this.
best regards

**Comment by marcelklehr** [comment]
I understand the problem. IMO the best approach is to fix the memory leak instead of implementing a kill switch for a certain memory usage. However, there should be system tools out there that allow to limit RAM usage of programs and will kill a program if it goes above a certain threshold.
