### ISSUE TITLE
command line tool to trigger a manual scan over all photos of all users would be nice to have.

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [marcelklehr/recognize#13]
command line tool to trigger a manual scan over all photos would be nice to have

**Comment by marcelklehr** [comment]
You mean, regardless of whether they have been tagged before? Or to avoid having the background job clog up CPU resources by manually controlling when it runs?

**Comment by MrLoverLoverMMMM** [comment]
Well the backgroundjob does not run the whole time (it runs in intervalls which are not configureable) and uses only 5 % of my cpu. Therefore it takes pretty long for 1,5 Million photos till all is finished. I would be happy if I could trigger a process to run through all photos, which not tagged yet, to tag all of them as fast as possible. I fpossible even with a bit more cpu usage.

**Comment by edo0** [comment]
The other way around, I had my RPi3B+'s 1GB RAM  (+ 1GB swap as well) going fully occupied for a few hours after installing the app. Nothing too serious in my case (only 2 users on my cloud setup), but still something a few people may like to get warned about beforehand.
I take the chance to also thank you very much for your work on this extension, the results are very good and it's definitely very very promising

**Comment by MrLoverLoverMMMM** [comment]
Well, a RPi3B+ is not a server, of course its resources are limited.
But for professional server hosting with more resources the app take much too less resources and takes very long to classify. Moreover, I found out that it does not check all pictures. It does not follow the whole depth of the path of folders in which can be pictures to classify, that's why I would wish a tool similar to files:scan that I can manually trigger a scan with classification for photos cross all files and folders independed on their depth and user.
Or maybe also with a parameter to tell the tool for which user or folder it should execute the classification.

**Comment by policywank** [comment]
I've installed two different point releases of this app over the last couple of months. I've installed and uninstalled twice over the last two months. The app doesn't seem to do anything at all in my installation.  Without some way of manually kicking off the scan, I don't even know when it's running to look for issues in the logs or to see a failure.

**Comment by marcelklehr** [comment]
Good points, all around. Thanks for your feedback. I'm currently somewhat swamped, so this'll sadly have to wait until I (or someone else) have time.

**Comment by marcelklehr** [comment]
[v1.3](https://github.com/marcelklehr/recognize/releases) now comes with a command line interface that allows running the classifier on full speed.

**Comment by mikweb2017** [comment]
@marcelklehr how to that?

**Comment by marcelklehr** [comment]
`occ recognize:classify`
