### ISSUE TITLE
First time running classification: Failed to classify images Bad Signature

### ISSUE THREAD

**Issue by tylnesh** [marcelklehr/recognize#131]
**Describe the bug**
Running "occ recognize:classify-images" fails and exits with the aforementioned message after listing all the files uploadedn on Nextcloud.

**To Reproduce**
1. Login via ssh
2. sudo -u www-data php /var/www/nextcloud/occ recognize:classify-images
3. Watch it list all the files

**Expected behavior**
Slowly but steadily classifying my images.

**Recognize (please complete the following information):**
 - JS-only mode: tried both, same result
 - Enabled modes: face and object detection

**Server (please complete the following information):**
 - Nextcloud: [23
 - OS: Ubuntu 20.04
 - RAM: 10GB
 - Processor Architecture x86 VPS

I was wondering if it was caused by some corruption due to the server-side encryption, however viewing and downloading files works.

**Comment by bonswouar** [comment]
> I was wondering if it was caused by some corruption due to the server-side encryption

Might be! We got an issue concerning encryption but closed it due to the lack of answer : #77

If I understand correctly it fails directly (no image is tagged)? Could you provide the full error log (if any)?

>  however viewing and downloading files works

Maybe you've got only one corrupted file, and that's the first one the command checks; although that would be very unlucky

**Comment by tylnesh** [comment]
At first it failed with just the message that I've put into the issue title. A few days later, I came back to see it processed 500 (out of 6500) images, while wrongfully tagging a few dozens. I though It! was working, albeit slowly, but after a few more days, there are no new processed or tagged images

**Comment by marcelklehr** [comment]
> Is there a way to get some more verbose output or log?

Can you check the nextcloud log?
