### ISSUE TITLE
Classifier process error

### ISSUE THREAD

**Issue by aerodb** [marcelklehr/recognize#134]
fresh install of the recognize app within nextcloud running on an unraid server. 

three errors show in the nextcloud log provided below. unsure what permission i need to grant for this to start scanning files. 

Warning | recognize | Classifier process error |   | 2022-01-15T19:05:28-0600
{"reqId":"ij2nATild2t2f4e07ckO","level":2,"time":"2022-01-16T01:05:28+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"23.0.0.10","id":"61e371fe95ffb"}

Warning | recognize | Classifier process errored |   | 2022-01-15T19:05:28-0600
{"reqId":"ij2nATild2t2f4e07ckO","level":2,"time":"2022-01-16T01:05:28+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: sh: exec: line 1: : Permission denied\n","userAgent":"--","version":"23.0.0.10","id":"61e371fe96098"}

Warning | recognize | Classifier process output: sh: exec: line 1: : Permission denied |   | 2022-01-15T19:05:28-0600
{"reqId":"ij2nATild2t2f4e07ckO","level":2,"time":"2022-01-16T01:05:28+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: sh: exec: line 1: : Permission denied\n","userAgent":"--","version":"23.0.0.10","id":"61e371fe96098"}

**Comment by bonswouar** [comment]
> running on an unraid server.

If I'm not mistaking, I'm sorry to tell you that we don't currently support unraid (alpine) : https://github.com/marcelklehr/recognize/issues/66

You can find more details about workarounds and/or add comments to the mentioned issue if you confirm it's related, I'll close this one then

**Comment by marcelklehr** [comment]
Running recognize at native speed doesn't work on Alpine Linux, but it should be able to run in JavaScript mode (which is much faster than it sounds, since v1.9.0). Also see [the requirements](https://github.com/marcelklehr/recognize#requirements).

**Comment by aerodb** [comment]
I wasnt aware that this wasnt supported within docker on unraid. after your suggestion @marcelklehr but it doesnt seem to be working either. Ill tinker a bit and see if i can get it running. Ill need to research the "System with glibc" portion. thank you all for the guidance.

**Comment by marcelklehr** [comment]
@aerodb If you're running nextcloud in docker the question becomes what OS is running in that container.

**Comment by aerodb** [comment]
The underlying OS is unraid, based on a Slackware distro of Linux. (I'm 80%sure of the distro)

**Comment by marcelklehr** [comment]
So, unraid in docker on unraid?

**Comment by marcelklehr** [comment]
If you're running nextcloud in docker the question becomes what OS is running *in* that container.

**Comment by aerodb** [comment]
I wasn't aware that was the architecture or nature of docker. I will need to research this a bit. Thank you for the guidance this far.

**Comment by marcelklehr** [comment]
If you like, you could post a link to the repository or docker hub entry of the container image you're using to host nextcloud :)

**Comment by aerodb** [comment]
Sure! this is the link to the linuxserver repository my nextcloud install was pulled from. https://github.com/linuxserver/docker-nextcloud  . Thank you for all the support thus far.

**Comment by marcelklehr** [comment]
They're using alpine: https://github.com/linuxserver/docker-nextcloud/blob/master/Dockerfile#L1

So, you can only run in JavaScript mode after setting a path to a custom node.js binary (that works on Alpine) in recognize settings.

**Comment by aerodb** [comment]
@marcelklehr to be clear, I must use a custom node.js binary, not the bundled node.js binary? also, setting a path within the docker template? do you have any documentation around this or how the path should be labeled?

thank you again in advance.

**Comment by marcelklehr** [comment]
Somehow, you'll need to make sure there is a node.js binary in that container that runs on Alpine.
Once that is the case, you can go into the nextcloud UI, to the settings for recognize and set the path to your custom node.js binary there. Then you enable JavaScript mode on the same page and recognize should be up and running.
