### ISSUE TITLE
Autodetect whether pureJS mode is necessary

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/recognize#136]

**Comment by marcelklehr** [comment]
@bonswouar Would you be amenable to implement this?

**Comment by bonswouar** [comment]
@marcelklehr Yes I can check this out! Do you know if looking for `avx` in `/proc/cpuinfo` would be enough?

**Comment by marcelklehr** [comment]
> Just noticed #133

Ah, yep. Forgot about that one :D

> Do you know if looking for avx in /proc/cpuinfo would be enough?

It should work, but I'm not sure, if the binaries require more instructions :/

**Comment by marcelklehr** [comment]
[Checking for AVX should be enough](https://www.tensorflow.org/install/pip#hardware-requirements)
