### ISSUE TITLE
Automatically reset tags when model is updated

### ISSUE THREAD

**Issue by bonswouar** [marcelklehr/recognize#140]
As discussed in #127,
We could add a parameter in the config to flag when the model has been updated in a release, updating should then reset all tags, so next scans will be a full scan

**Comment by jgonsior** [comment]
Better than first deleting all tags and rendering therefore automatically a full scan (which can take quite a while for large photo collections) would be maybe to add something like a new hidden tag (f. e. the version of the ML model) to all existing files, and then gradually only remove the old tags (including the new hidden tag) and replace them with newly computed tags?

**Comment by marcelklehr** [comment]
@jgonsior This is a brilliant idea!

**Comment by bonswouar** [comment]
I like the idea too, although I don't know much about nextcloud tag api. @marcelklehr Are you sure there is a way to add hidden tags?
I looked into https://github.com/nextcloud/server/blob/master/lib/private/Tags.php but didn't find anything

**Comment by marcelklehr** [comment]
This is how we create the hidden, admin-only Tagged by recognize tag: https://github.com/marcelklehr/recognize/blob/master/lib/Service/TagManager.php#L40

**Comment by bonswouar** [comment]
Thanks, I've never noticed as I've always used NC as an admin :smile: 
I'll probably look into implementing this feature then!
