### ISSUE TITLE
Internal server error / exec format error after updating

### ISSUE THREAD

**Issue by stephen304** [marcelklehr/recognize#143]
**Describe the bug**
When trying to view the recognize settings, I get an internal error screen. I checked the logs and it says
    sh: 1: /var/www/html/custom_apps/recognize/bin/node: Exec format error

I checked in that volume and I can execute the node binary fine

    node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=3d052a3d1391f7d7e13f3b9f33f7ebc1dd4ff449, with debug_info, not stripped

    ./node --version
    v14.18.2

**To Reproduce**
1. Update recognize to latest version
2. Visit settings > recognize

**Expected behavior**
No error

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: All

**Server (please complete the following information):**
 - Nextcloud: 23.0.0
 - OS: Docker on Ubuntu 21.10 VM on Truenas
 - RAM: 8GB
 - Processor Architecture x86

Additional info:

I also tried uninstalling / reinstalling recognize, restarting the app container in between. I made sure the custom_app recognize folder was being completely removed.

**Comment by marcelklehr** [comment]
Does it help to run `occ upgrade`?

**Comment by stephen304** [comment]
Unfortunately that just outputs "nextcloud is already latest version". The
other odd thing is that after I hit the plugin upgrade for recognize, after
waiting a while the whole ui went to a full screen upgrade screen. If NC 23
just dropped I may have accidentally upgraded - otherwise I'm not sure what
it was. I didn't update the docker container for anything because I was
just expecting a quick plugin update.

--
Stephen Smith
Software Engineer

**Comment by stephen304** [comment]
Actually it turns out that was it. Looks like v23 dropped within the last 24 hours so I pulled and re-dockercompose-upped and it looks like it's working now. Somehow the plugin upgrade upgraded my NC too? After re-pulling I didn't get an upgrade wizard and it said already up to date so I guess container/app version mismatch was it.

**Comment by marcelklehr** [comment]
> If NC 23 dropped I may have accidentally upgraded

Wow, that sounds like a bug. I certainly don't want to upgrade to v23 on prod right now :sweat_smile:
