### ISSUE TITLE
Permission denied error when manually running classify images

### ISSUE THREAD

**Issue by Ritter99** [marcelklehr/recognize#144]
I am getting the following error message when I run `occ recognize:classify:images`

```
Running array (
  0 => '',
  1 => '/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
sh: taskset: not found
Classifier process output: sh: exec: line 1: : Permission denied

Classifier process output: sh: exec: line 1: : Permission denied

Failed to classify images
Classifier process error
```

 - JS-only mode: No
 - Enabled modes: [object detection, face recognition, landmark recognition, music genre recognition]

 - Nextcloud: 22.2.3
 - OS: Linux 5.11.0-43-generic
 - RAM: 15.63GB
 - Processor Architecture: x86

- Running inside docker: linuxserver/nextcloud:latest

**Comment by marcelklehr** [comment]
The container you are using is based on Alpine Linux, which doesn't have glibc and thus cannot execute the node.js version that comes bundled with the app. You can either set the path to a working node.js binary in the app settings, or wait for recognize to support Alpine linux out of the box.

See #66
