### ISSUE TITLE
Tags are shown for every user - even if user has no such tagged images

### ISSUE THREAD

**Issue by Maulwurf16** [marcelklehr/recognize#15]
I have two users in my nextcloud instance:
- me myself (admin rights)
- another user

The app started to scan the images of the other user first - everything works great here :)

However, as the photos are scanned in the second account, also the tags are shown in the first (admin) account. Here, of course, they are no photos behind those tags (yet).

<img width="607" alt="Bildschirmfoto 2021-05-03 um 09 43 07" src="https://user-images.githubusercontent.com/4345240/116852081-fd4cbf00-abf3-11eb-8c2c-944049bb7625.png">

Expected behavior would be: Only show the tags, when there are tagged photos in that account.

**Comment by marcelklehr** [comment]
This would be a problem with the photos app. There's an issue about reworking collaborative tags over here: https://github.com/nextcloud/server/issues/4699
