### ISSUE TITLE
SOLVED - Got this Running on Docker/UNRAID which should have been easier. 

### ISSUE THREAD

**Issue by BostonGman** [marcelklehr/recognize#150]
BUG:  Lack of proper documentation is all

REPRODUCE
The error occurs when you run "occ recognize:classify-images"  it fails, with permission errors. 
ROOT CAUSE:
The root cause of this error is that the Docker ([lscr.io/linuxserver/nextcloud) build does not have glibc installed through it's alpine distro.  

FIX:
    ENABLE - Enable JavaScript mode
    PASTE INTO Node.js Path - /config/www/nextcloud/apps/recognize/bin/node 
    RUN  -  inside the Docker run : occ recognize:classify-images    

WAIT:  30 seconds or so
     Tooks a few seconds for me and you see recognize start with tag information on the images. 

Please update the Documentation as this "/config/www/nextcloud/apps/recognize/bin/node"  binary was already created with the installation of the NextCloud App installation process,   I spent hours look for a solution on google, forums and such,  no luck.   I even tried to install GlibC,  a remote Node.js Binary.   While fun,  the solution was so easy that the binary was already present in the build,  just place that information or possible drop-down in the Node.js  PATH field.    Unless there is a reason not to use the node.js at this location ?

Cheers and great App guy. 

-C

**To Reproduce**

**Expected behavior**

**Recognize (please complete the following information):**
 - JS-only mode: [e.g. Yes/No]
 - Enabled modes: [e.g. object detection, face recognition]

**Server (please complete the following information):**
 - Nextcloud: [e.g. 21.0.4]
 - RAM: [e.g. 16GB]
 - Processor Architecture [e.g. x86, ARM64, etc. ]

**Additional context**

**Comment by marcelklehr** [comment]
> Unless there is a reason not to use the node.js at this location ?

What was the value of that input field for you before you changed it? It should be set to recognize/bin/node by default

**Comment by BostonGman** [comment]
It was just blank...

Sent on the Go.  #DriveSafe

**Comment by marcelklehr** [comment]
Was this a new install or did you update?

**Comment by BostonGman** [comment]
The issue presented itself on a fresh install I even tried uninstalling and
reinstalling.   Node.js path field is always empty.



Sent on the Go.  #DriveSafe

**Comment by BostonGman** [comment]
I was able to reproduce it,  but tracking down a more direct path.

I created another instance of nextcloud and then started comparing apps,
checking one by one - the good news;  this was fine using the default admin
account.   However, after all the apps were installed I create a second
admin account and that's when it disappeared.     Working on the exact
issue but I am getting closer for you.

-Corey

**Comment by marcelklehr** [comment]
Mmh. Maybe that new user doesn't have all the rights, or isn't perceived to have them. Could you check the Network tab in the browser inspector on that settings page?

**Comment by ados8** [comment]
I'm unable to get it working on UNRAID too
I get `occ: not found`

![image](https://user-images.githubusercontent.com/49982433/155867798-32904f37-9bb7-412c-b891-8c25339ce427.png)

I have tried with and without Java mode
I have no GPU just x64 Intel CPU

**Comment by marcelklehr** [comment]
@ados8 This may help: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html

@ados8 Also, make sure to run the command *inside* the container.

**Comment by ados8** [comment]
So trial and error later I got further but it now errors

`Running array (
  0 => '/var/www/html/custom_apps/recognize/bin',
  1 => '/var/www/html/custom_apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: sh: 1: exec: /var/www/html/custom_apps/recognize/bin: Permission denied

Classifier process output: sh: 1: exec: /var/www/html/custom_apps/recognize/bin: Permission denied`

This happens with and without Java mode
I have even tested with chmod 777 on the entire directory of app and still denied
User is: www-data which is required for the osc to run in the docker consol

**Comment by marcelklehr** [comment]
> based on the requirements its not supported with UNRAID based of FreeBSD

When running nextcloud in docker, what matters is the OS *in* the docker container.

**Comment by bonswouar** [comment]
I guess we can close this?

As a side note, @marcelklehr it might be useful to add some specific information about UNRAID/Docker systems _(native speed incompatibility for both as Nextcloud's official Docker container uses Alpine; and maybe a little reminder on how to use container's user commands)_ in the README
It's not required but as this repo seem to often mean to use OCC commands for the first time for lots of users, it can be a nice bonus! (which could save them a lot of time and prevent some new issues)

**Comment by marcelklehr** [comment]
@bonswouar a little explainer might be worthwhile indeed
