### ISSUE TITLE
Specify batch size for image classification command

### ISSUE THREAD

**Issue by solonovamax** [marcelklehr/recognize#154]
**Describe the bug**
Currently, when invoking the image classification command, it will attempt to classify all the images at once. This is problematic in low-memory environments. (Note: this does **not** occur for the cron job)

The cron job seems to run fine before terminating, but invoking it directly via the CLI seems to lead to the following log output:
```
  2965 => '/tmp/oc_tmp_LD9Z2v-.jpg',
  2966 => '/tmp/oc_tmp_rttQ0v-.jpg',
  2967 => '/tmp/oc_tmp_uieOEu-.jpg',
  2968 => '/tmp/oc_tmp_pH6RFv-.jpg',
  2969 => '/tmp/oc_tmp_VBDDls-.jpg',
)
Running array (
  0 => '/var/www/nextcloud/apps/recognize/bin/node',
  1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: 2022-02-21 15:08:56.204793: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Classifier process output: 2022-02-21 15:09:08.838000: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 115654656 exceeds 10% of free system memory.

Classifier process output: 2022-02-21 15:09:09.427992: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.

Classifier process output: 2022-02-21 15:09:10.371516: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.

Classifier process output: 2022-02-21 15:09:12.054620: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.

Classifier process output: 2022-02-21 15:09:13.179369: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.

Classifier process output: 2022-02-21 15:08:56.204793: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-02-21 15:09:08.838000: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 115654656 exceeds 10% of free system memory.
2022-02-21 15:09:09.427992: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.
2022-02-21 15:09:10.371516: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.
2022-02-21 15:09:12.054620: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.
2022-02-21 15:09:13.179369: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 462618624 exceeds 10% of free system memory.

Failed to classify images
Classifier process error
```

See "server" section for my server specs

**To Reproduce:**
1. Create a low memory nextcloud environment with recognize installed.
2. Add a lot of images. (When this occured for me, it was attempting to classify ~3000 images)
3. Invoke `./occ recognize:classify-images`
4. Process will crash with above output.

**Expected behaviour:**
Process shouldn't crash because of an OOM, even though the cron job seems to run fine.

**Recognize:**
 - JS-only mode: no
 - Enabled modes: all

**Server:**
 - Nextcloud: 23.0.0.10
 - OS: Debian 5.10.92-1
 - RAM: 4GB
 - SWAP: 4GB
 - Processor Architecture x86_64

**Additional Info:**
Originally, I was attempting to run the classification simply with my 4GB of ram and little to no swap (my hosting provider gave me a default of 512MB and I didn't change that), but it was ending with this error. So, I bumped the swap up to 4GB, but it still exited with this error, even though the README specifies that 4GB should be sufficient.

This, in addition to how it won't fail from the cron job leads me to believe that the cause for the OOM is because it is attempting to process too many images at once.

An alternative to processing them all at the same time would be to batch the images, and then just do a `while` loop until all images have been processed in batches of `x` size.

**Comment by bonswouar** [comment]
I believe there are still some memory leaks from nodejs processing.
As a workaround adding an optional parameter to the command would certainly do the trick, but I'm not sure it would make much sense (how would someone guess how many images he should process at a time?).
And as @marcelklehr said in [another issue](https://github.com/marcelklehr/recognize/issues/128#issuecomment-1007287228):
> IMO the best approach is to fix the memory leak instead of implementing a kill switch for a certain memory usage. However, there should be system tools out there that allow to limit RAM usage of programs and will kill a program if it goes above a certain threshold.

**Comment by solonovamax** [comment]
@bonswouar 
> As a workaround adding an optional parameter to the command would certainly do the trick

Yes, I agree that adding an optional parameter to specify the max number of images processed would be a good temporary solution until the mem leak is fixed. Could this be implemented at some point, as it seems like the mem leak is taking a while to fix?

**Comment by marcelklehr** [comment]
Since OOM could also stem from the sheer volume of file paths, I've constructed a fix that will classify the files in batches of 500 when run from the CLI.

**Comment by solonovamax** [comment]
it would be great if it could instead be a configurable batch amount. I haven't tested it, but 500 *should* work for me. But, configurable = better, imo

**Comment by marcelklehr** [comment]
I know.. In general, users want config options, developers don't. :smile: 
In this case it shouldn't matter whether it's a config option, because there is no penalty for people that don't need a small batch size, so if it doesn't work, you can come back here and we'll reduce it even more, so it works for everyone.

**Comment by Murazaki** [comment]
Doesn't work for me 😭😂
Docker config on a Debian bullseye server, I actually changed from `nextcloud:fpm-alpine` to `nextcloud:fpm` to make it work
Tried WASM and native, current and new version of node, to no avail

> www-data@app:~/html$ php occ recognize:classify-images
Collecting photos of user admin
Searching files
Searching files/Talk
No unclassified photos found by user admin
Collecting photos of user ...
Searching files
Searching files/Documents
...
Searching files/Photos
...
Searching files/Talk
Searching files/Templates
...
Classifying photos of user ... using imagenet
Classifying array (
...
)
Running array (
  0 => '/var/www/html/custom_apps/recognize/bin/node',
  1 => '/var/www/html/custom_apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: 2022-07-12 16:21:04.286350: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>
>Classifier process output: 2022-07-12 16:21:04.286350: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

I have a basic GPU card in there though  (Cedar Radeon) but the processor is recent (AMD Ryzen 5 1600 AF)
