### ISSUE TITLE
Admin Settings Interface

### ISSUE THREAD

**Issue by policywank** [marcelklehr/recognize#17]
It would be great if there were something in the Recognize page under the settings-->administration menu to let you know if the app is correctly installed and able to scan storage.

(And if that does exist, then it's a great sign that my installs have always failed, because I just get a blank page.)

**Comment by marcelklehr** [comment]
There is no content there, yet. But it's planned, of course :)

**Comment by dirad** [comment]
maybe ... https://github.com/marcelklehr/recognize/issues/13
