### ISSUE TITLE
Failed at the ffmpeg-static@4.4.0 install script

### ISSUE THREAD

**Issue by PadseGaming** [marcelklehr/recognize#180]
Hi im new, my Name is Paddy. Install Failed after make. I dont understand what to do. Which Modul i have to add and where?

 root@nextcloudpi:/home/paddy# cd /var/www/nextcloud/apps/recognize
root@nextcloudpi:/var/www/nextcloud/apps/recognize# make
rm -rf js
rm -rf /var/www/nextcloud/apps/recognize/build/artifacts/sign
rm -rf node_modules
npm ci
> ffmpeg-static@4.4.0 install /var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static
> node install.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-static@4.4.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-static@4.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-24T11_28_25_416Z-debug.log
make: *** [Makefile:24: npm-init] Error 1
root@nextcloudpi:/var/www/nextcloud/apps/recognize#

**Recognize (please complete the following information):**
 Nothing. Can Install but the settings Page is empty, Show nothing.

**Server (please complete the following information):**
 - Nextcloud: 23.0.3
 - OS: [Debian nextcloudpi Image
 - RAM: [4gb]
 - Processor Architecture Linux 5.15.27-v8+ aarch64 (Raspberry 4b 4gb)

**Comment by marcelklehr** [comment]
Hi Paddy and welcome :wave: 

I sadly can't replicate this. What is your npm and node version? I recommend node v14+ and npm v7+ at the time of writing.

**Comment by PadseGaming** [comment]
Hi Marcel,

Node is 14.19.1. But i also tryed with 16+.

Nvm wasnt at 7+. I've installed it and now it works. But i still have the
following Problem and cant find a solution:

  41024 =>
'/media/myCloudDrive/ncdata/data/USER/files/FOLDER/FOLDER/.thumbnails/61868.jpg',
)
Running array (
  0 => '',
  1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: sh: 1: exec: : Permission denied

Classifier process output: sh: 1: exec: : Permission denied

Failed to classify images
Classifier process error
***@***.***:/var/www/nextcloud#


Marcel Klehr ***@***.***> schrieb am Do., 24. März 2022,
14:36:

**Comment by marcelklehr** [comment]
> Nvm wasnt at 7+. I've installed it and now it works. 


Great!

>   0 => '',

You need a working node.js binary in the recognize folder. The easiest method is probably to disable and enable the app once, for the install routine to kick in and download and register the appropriate one.

**Comment by PadseGaming** [comment]
Wow! Thanks for ur help Marcel! That easy solution helped!  Now the Manual command does his Job :) 

Do i have to run it first Time manuell until all Pictures are classified?  Or is there a way to do it automatically? 

I dont find any discription how the classify works automatically after the App is installed correctly. 

Should i add the manuell command for classify to the cronjob? Or will the classify Starts automatically at anytime? 

I think it will be a good explain to ur App description. I missing such a hint, how to automatic classifying. :) 

Best regards Paddy

**Comment by marcelklehr** [comment]
The app has a settings page in the nextcloud admin settings, which should be quite self-explanatory :) I'll add that hint to the description.
