### ISSUE TITLE
Tagged Photos page is empty

### ISSUE THREAD

**Issue by dirad** [marcelklehr/recognize#19]
A few hours after my photos have been uploaded and the app installed, still my tags view has no photos.
The files are 2 folders under the base directory.

my whole data folder is on /mnt/folder

Is there a log?
How do I know what is happening? 

thanks

**Comment by marcelklehr** [comment]
The app logs errors to the nextcloud log. I'm not sure if it supports a mounted data folder, yet.

**Comment by millenseer** [comment]
On my Server, running Nextcloud 21.0.2 and recognize Version 1.3.1, the tag page is empty and the settings page as well:
apps/photos/tags/beach -> empty  (tried some basic tags)
settings/admin/recognize -> empty

I guess, the recognizer must index the images. But how do I start this?

**Comment by escoand** [comment]
@millenseer Have the same problem but hadn't the time to create an issue yet. I could see error in the browser's developer console (F12 key).

**Comment by millenseer** [comment]
Ok, I was too hasty. Over night the image tagger was able to tag my images. Wow. Some tags are funny, others are perfect!

Again, how do I start the index/tagging mechanism? Or how does it work in the backend?
The page settings/admin/recognize is still empty.

**Comment by escoand** [comment]
Not sure if we're talking about the same thing - I'm talking about the settings page with the following error: `Loading failed for the <script> with source “https://.../apps/recognize/js/recognize-admin.js?v=75d5b298-13”.`

**Comment by marcelklehr** [comment]
> Again, how do I start the index/tagging mechanism?

It runs automatically in the background. If you want to run it in cli, you can use `occ recognize:classify`

> The page settings/admin/recognize is still empty.

This is by design.

**Comment by marcelklehr** [comment]
@escoand Some tags are funny, others are perfect!

Feel free to add a summary of wonky tags over at #24
