### ISSUE TITLE
Tagging takes forever

### ISSUE THREAD

**Issue by derritter88** [marcelklehr/recognize#20]
Hello @marcelklehr ,

I have installed the app last Friday and since then it is stuck with tagging only one use and not all.
Not sure if tagging takes so long or if there is any other issue.

**Comment by marcelklehr** [comment]
> it is stuck with tagging only one use and not all.

I'm not sure I understand you

**Comment by derritter88** [comment]
In my Nextcloud log I see randomly a line saying "regonize for user xxx" but it stuckt with this single user.
No other user is being used.

**Comment by marcelklehr** [comment]
Do you see tags being added? If tags are being added, then that's as fast as it can go in a background task. I'm working on a cli command that will do everything at once.

**Comment by marcelklehr** [comment]
The tagging speed depends on your hardware performance specs and the amount of images you have.

**Comment by derritter88** [comment]
> 
> 
> Do you see tags being added? If tags are being added, then that's as fast as it can go in a background task. I'm working on a cli command that will do everything at once.

I just had a look at the "real" log -> nextcloud.log and not just the online log display.
I can see that there is a progress - slowly but working.

Regarding hardware specs:
VM
24 GB RAM
8 cores (Epyc 7272)
~ 700 GB cloud storage


So I guess I just need to wait.

**Comment by derritter88** [comment]
Just for info: The GUI says `


Warning | recognize | Classifying photos of user mhepp
-- | -- | --




`

**Comment by marcelklehr** [comment]
[v1.3](https://github.com/marcelklehr/recognize/releases) now comes with a command line interface that allows running the classifier on full speed.

**Comment by derritter88** [comment]
Thanks for the information - will do the update right now!

May I ask: Is this application only using the CPU or is it also able to use an existing GPU?

**Comment by marcelklehr** [comment]
It currently only uses CPU. But by default the cli will use all your CPUs, you can however also set a custom amount of CPUs.

**Comment by marcelklehr** [comment]
The admin user has access to a tag called "Tagged by recognize".

**Comment by derritter88** [comment]
> 
> 
> It currently only uses CPU. But by default the cli will use all your CPUs, you can however also set a custom amount of CPUs.

Would be great if this application would be able to use a GPU.
May I ask which php library your application uses?


Regarding cli: Is it better to create a dedicated cronjob for having the photo recognized or could this be done via the regular Nextcloud cronjob?

**Comment by derritter88** [comment]
@marcelklehr regarding my library question:
Unfortunately I am not so deep into development - just remembered some Java stuff I have "developed" at high school.

May I just ask if pdlib would be suitable for this application?
https://github.com/goodspb/pdlib

**Comment by marcelklehr** [comment]
> Is it better to create a dedicated cronjob for having the photo recognized or could this be done via the regular Nextcloud cronjob?

I think the point of the cli is to do the initial bulk of photo classification, while the background job should be able to handle new photos as they are uploaded. If the background job is not enough, you can schedule the cli to run every night perhaps.

> Would be great if this application would be able to use a GPU.

It's definitely possible, you can open a new issue for that.

> May I ask which php library your application uses?

I'm using tensorflow-js running inside Node.js.
