### ISSUE TITLE
Not original owner of ... (external drive)

### ISSUE THREAD

**Issue by Sputnikchen** [marcelklehr/recognize#201]
![FireShot Capture 001 - Einstellungen - Nextcloud - 169 254 237 11](https://user-images.githubusercontent.com/72913328/166094992-5e1aa557-8873-45d7-b7b5-dd2fb0fe2865.png)
Scan is working for internal files.
scanning the external drive (bind: /external/drive/Fotos) for each file I get the message:
`Not original owner of /myname/files/Fotos/folder/photo.jpg`
 ```
ls -l /external/drive/Fotos/folder
-rwxr--r-- 1 www-data www-data 227662  5. Okt 2014  pic_1.jpg
drwxr--r-- 2 www-data www-data   4096 29. Mär 15:54  subfolder
```

```
 ls -l data/myname/files/Photos
-rw-r--r-- 1 www-data www-data   232876 15. Aug 2021   mypic.jpg
drwxr-xr-x 2 www-data www-data     4096 24. Apr 13:36  folder2
```

```
 sudo -u www-data php ./occ recognize:classify-images
Collecting photos of user myname
Searching files
[...]
Searching myfolder
Not original owner of /myname/files/Fotos/folder/Schloss.jpg
```
Can't find a solution. Bug?

**Comment by Sputnikchen** [comment]
After thousands of errors, at the end of the scan apears:
```
[...]
Passing 
Classifying photos of user myname using imagenet
Classifying array (
  0 => '/external/drive/www/nextcloud/data/myname/files/Nextcloud.png',
  1 => '/external/drive/www/nextcloud/data/__groupfolders/1/myname/ebooks/cover.jpg',
[...]
)
Running array (
  0 => '/usr/bin/node',
  1 => '/external/drive/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js
- /external/drive/www/nextcloud/apps/recognize/src/classifier_imagenet.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js',
    '/external/drive/www/nextcloud/apps/recognize/src/classifier_imagenet.js'
  ]
}

Classifier process output: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js
- /external/drive/www/nextcloud/apps/recognize/src/classifier_imagenet.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js:18:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/external/drive/www/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js',
    '/external/drive/www/nextcloud/apps/recognize/src/classifier_imagenet.js'
  ]
}

Failed to classify images
Classifier process error
```

**Comment by debian-user-france1** [comment]
I think it is not supported yet.

**Comment by Sputnikchen** [comment]
It worked in Nextcloud 22 befor I've installed the new server with NC 23. At the same machine.
`Linux kobol 5.15.25-rockchip64 #22.02.1 SMP PREEMPT Sun Feb 27 09:05:47 UTC 2022 aarch64 GNU/Linux`

**Comment by WXpiero** [comment]
seems like same situation here:

 494 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-09-28.png',
  495 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-09-35.png',
  496 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-09-39.png',
  497 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-11-30.png',
  498 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-11-32.png',
  499 => '/srv/nextcloud/data/proxprox/files/Photos/DICM/Screenshots/Screenshot_2014-03-03-21-13-22.png',
)
Running array (
  0 => '',
  1 => '/srv/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: sh: 1: exec: : Permission denied

Classifier process output: sh: 1: exec: : Permission denied

Failed to classify images
Classifier process error
root@VM-8-14-debian:/srv/nextcloud/apps/recognize# ls -all /srv/nextcloud/apps/recognize/src
total 128
drwxr-xr-x  7 www-data root  4096 May  1 08:38 .
drwxr-xr-x 16 www-data root  4096 May  1 09:31 ..
-rw-r--r--  1 www-data root   475 May  1 08:38 admin.js
-rw-r--r--  1 www-data root  4165 May  1 08:38 classifier_faces.js
-rw-r--r--  1 www-data root  1496 May  1 08:38 classifier_geo.js
-rw-r--r--  1 www-data root  4787 May  1 08:38 classifier_imagenet.js
-rw-r--r--  1 www-data root  3890 May  1 08:38 classifier_landmarks.js
-rw-r--r--  1 www-data root  4225 May  1 08:38 classifier_musicnn.js
drwxr-xr-x  2 www-data root  4096 May  1 08:38 components
drwxr-xr-x  2 www-data root  4096 May  1 08:38 efficientnet
drwxr-xr-x  2 www-data root  4096 May  1 08:38 landmarks
-rw-r--r--  1 www-data root     0 May  1 08:38 main.js
drwxr-xr-x  2 www-data root  4096 May  1 08:38 mixins
-rw-r--r--  1 www-data root   662 May  1 08:38 model-manager.js
drwxr-xr-x  2 www-data root  4096 May  1 08:38 musicnn
-rw-r--r--  1 www-data root   604 May  1 08:38 musicnn_rules.yml
-rw-r--r--  1 www-data root 53533 May  1 08:38 rules.yml

**Comment by Sputnikchen** [comment]
You've a permission problem:
> Classifier process output: sh: 1: exec: : Permission denied

Normally you should get something like this:
```
Classifier process output: {
  className: 'digital clock',
  probability: 0.020943865180015564,
  rule: { threshold: 1, label: 'clock' }
}
```
My internal files are working
```
Collecting photos of user myname
Searching files
Searching files/Documents
Found /myname/files/Documents/Logo/Logo_red.jpg
Searching files/Photos
ound /myname/files/Photos/Birdie.jpg
[...]
Passing 
Classifying photos of user myname using imagenet
Classifying array (
  0 => '/path/to/www/nextcloud/data/myname/files/Documents/Logo/Logo_red.jpg',
[...]
  198 => '/path/to/www/nextcloud/data/myname/files/Photos/Birdie.jpg,
)
Running array (
  0 => '/media/raid/www/nextcloud/apps/recognize/bin//node',
  1 => '/media/raid/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: {
  className: 'envelope',
  probability: 0.39271989464759827,
  rule: { label: 'office', threshold: 0.2 }
}
[...]
```
after that (classifier_imagenet.js)
classifier_faces.js is starting.

**Comment by marcelklehr** [comment]
@WXpiero please open a new issue

**Comment by teamfighter** [comment]
+1 for that

**Comment by nuk3s** [comment]
+1  I am having the same issue as well

**Comment by alfwro13** [comment]
+1 here as well - all my photos are on external storage linked to NC using the External Storage app
