### ISSUE TITLE
Unable to open /proc/cpuinfo at installation

### ISSUE THREAD

**Issue by Glandos** [marcelklehr/recognize#209]
**Describe the bug**
`InstallDeps.php` is unable to open `/proc/cpuinfo` on a hardened system

```
file_get_contents(/proc/cpuinfo): failed to open stream: No such file or directory at /var/www/cloud.example.com/nextcloud/apps_writable/recognize/lib/Migration/InstallDeps.php#181
```

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: N/A

**Server (please complete the following information):**
 - Nextcloud: 22.0.3
 - OS: Debian
 - RAM: 4GB
 - Processor Architecture: Intel(R) Atom(TM) CPU D2550   @ 1.86GHz

**Additional context**
The system is hardened, so `/proc/cpuinfo` is unreadable.

**Comment by Glandos** [comment]
OK, that was faster than I ever expected.

**Comment by marcelklehr** [comment]
heh, sometimes things move fast :)

**Comment by Vuk996** [comment]
The error also occurs with me on a shared web server: 25.0.0 RC2

Fehler	index	Exception: str_contains(): Argument #1 ($haystack) must be of type string, bool given in file '/var/www/vhosts/.../httpsdocs/nextcloud/apps/recognize/lib/Migration/InstallDeps.php' line 192	
Fehler	PHP	Error: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/.../httpsdocs/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#188	
Fehler	PHP	Error: file_get_contents(): open_basedir restriction in effect. File(/proc/cpuinfo) is not within the allowed path(s): (/var/www/vhosts/.../:/tmp/:/var/lib/php/sessions) at /var/www/vhosts/.../httpsdocs/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#188
