### ISSUE TITLE
misspelling of audio recognition status and status not shown but recognition works

### ISSUE THREAD

**Issue by debian-user-france1** [marcelklehr/recognize#211]
![image](https://user-images.githubusercontent.com/72965843/169104342-9251a4e7-1b2c-44da-9d20-6cee4a1e9ddb.png)

1. There's no space between 30 and minutes.
2. All audio files were classified but it doesn't show any status.
3. I didn't see anything in the logs but may have overseen something. I used grep to search for audio and recognition.

**Comment by debian-user-france1** [comment]
> Does the status change when refreshing the page? Otherwise the status mechanism probably has a bug.

It does not. I am not sure though if there's any audio on the nextcloud. You should probably correct the spelling first...
Yeah, maybe it's because there's no audio file stored yet.

**Comment by marcelklehr** [comment]
There is likely no audio in your nextcloud, which is why the status doesn't change. It may have processed image files but no audio files. Typo is fixed now :)

**Comment by debian-user-france1** [comment]
No. There is. MP3, since a while.

**Comment by debian-user-france1** [comment]
Huh? Now I get a failed to load settings, refreshing doesn't help.
