### ISSUE TITLE
[core] Fehler: OC\User\NoUserException: Backends provided no user object at <<closure>>

### ISSUE THREAD

**Issue by IkariDevGIT** [marcelklehr/recognize#213]
[core] Fehler: OC\User\NoUserException: Backends provided no user object at <<closure>>

0. <<closure>>
   OC\Files\Node\Root->getUserFolder()
1. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 72
   call_user_func_array()
2. /var/www/nextcloud/lib/private/Files/Node/LazyRoot.php line 40
   OC\Files\Node\LazyFolder->__call()
3. /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php line 50
   OC\Files\Node\LazyRoot->getUserFolder()
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 47
   OCP\BackgroundJob\Job->execute()
6. /var/www/nextcloud/cron.php line 174
   OCP\BackgroundJob\QueuedJob->execute()

GET /cron.php
from ********* at 2022-05-19T16:20:53+00:00

**Comment by marcelklehr** [comment]
Hello @IkariDevGIT 

This appears to be an issue with https://github.com/nextcloud/maps instead of this project: `/var/www/nextcloud/apps/maps/BackgroundJob/UpdatePhotoByFileJob`
