### ISSUE TITLE
App is shipping node_modules and is insanely huge

### ISSUE THREAD

**Issue by skjnldsv** [marcelklehr/recognize#224]
The app is shipping node modules. Are they really all necessary?
Last release is 133MB (compressed). 

Can't we compile the various classifiers as runtimes and avoid executing them from `src` ?
We would gain a lot. Rollup can help I think

A subsidiary issue, installing this app on a distributed storage took me 15 minutes for all thousands of files being distributed accross all nodes (small files are slow, even on high-speed ssds) :wink:

**Comment by skjnldsv** [comment]
I mean, we should compile the [classifiers](https://github.com/marcelklehr/recognize/blob/master/src/classifier_faces.js) into dist files and avoid shipping  node_modules.

**Comment by marcelklehr** [comment]
Ah, that'd be neat

**Comment by marcelklehr** [comment]
For now I've sorted the client-side deps into devDependencies to only ship the server-side modules, which sliced the bundle size in [half](https://github.com/marcelklehr/recognize/releases/tag/v2.1.0). Using rollup is [probably not gonna work as tensorflow needs native node modules](https://github.com/rollup/rollup/issues/3504).
