### ISSUE TITLE
Log file overloaded

### ISSUE THREAD

**Issue by animalillo** [marcelklehr/recognize#225]
**Describe the bug**
Log file flooded with logs and causing a lot of log rotation and consequent disk filling.
> Log file "/var/www/nextcloud/data/nextcloud.log" was over 104857600 bytes, moved to "/var/www/nextcloud/data/nextcloud.log.1"

**To Reproduce**
1. Go to /settings/admin/recognize
2. Wait eternally for the status numbers to show while they slowly show up
3. Open logs to check
4. Nothing shows up, but suddenly the log file is being rotated.
5. Download log file and see it filled with debug logs like:
```json
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Not a supported format: /some/path/Manual.pdf","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Already processed /some/path/Nextcloud.png","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Searching files/Notes","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Searching files/Photos","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Already processed /someone/path/Photos/Birdie.jpg","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Already processed /someone/path//Photos/Frog.jpg","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:09+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Already processed /someonelse/path/Photos/Gorilla.jpg","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:10+00:00","remoteAddr":"","user":"someone","app":"recognize","method":"","url":"--","message":"Already processed /someonelse/path/Photos/Library.jpg","userAgent":"--","version":"22.2.3.0"}
{"reqId":"xRyDiqns5u1uHLWHbQ78","level":0,"time":"2022-06-01T08:31:10+00:00","remoteAddr":"","user":"soneone","app":"recognize","method":"","url":"--","message":"Already processed /someonelse/path/Photos/Nextcloud community.jpg","userAgent":"--","version":"22.2.3.0"}
```

**Expected behavior**
Logs not clogging the hard drive.

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: All

**Server (please complete the following information):**
 - Nextcloud: 22.2.3
 - OS: Ubuntu 20.04.4 LTS
 - RAM: 8GB
 - Processor Architecture: x86_64 kvm processor with fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 pcid x2apic hypervisor lahf_lm cpuid_fault pti

**Additional context**
It seems that the user is incorrect while processing directories from other users. Unsure if related, i don't think so, but may have some implications beyond my understanding, so worth noting here.

Also worth noting i just updated the app.

**Comment by marcelklehr** [comment]
It should be possible to set the log level you want to see, i.e. exclude debug logging to avoid it filling the logs.

**Comment by skjnldsv** [comment]
> **Describe the bug** Log file flooded with logs and causing a lot of log rotation and consequent disk filling.
> 
> > Log file "/var/www/nextcloud/data/nextcloud.log" was over 104857600 bytes, moved to "/var/www/nextcloud/data/nextcloud.log.1"

You should disable debug logging if you don't want an overflow of entries.
