### ISSUE TITLE
Unable to select video recognition

### ISSUE THREAD

**Issue by Kbrown901** [marcelklehr/recognize#237]
**Describe the bug**
Unable to enable video recognition. Box is not greyed out just does not respond to trying to enable this feature and only this feature.

**To Reproduce**
1. Go to settings
2. Scroll down the left panel to “Recognize” and click
3. Scroll to video recognition and click the unchecked box

**Expected behavior**
Expected for the checkbox to indicate video recognition is enabled, only to have absolutely no change.

**Recognize (please complete the following information):**
 - JS-only mode: default 
 - Enabled modes: face recognition, location tagging, object recognition, landmark recognition, music genre recognition 

**Server (please complete the following information):**
 - Nextcloud: 24.0.2
 - OS: Ubuntu Server 21.10
 - RAM: 32GB
 - Processor Architecture: AMD FX-8350 eight core @ 4Gh

**Additional context**
All other recognize features work, has processed thousands of photos and music with no problems attempted to run manually through terminal and the occ command which also does nothing. After hitting enter for the command I just get a new line for another command as if it successfully ran the command within milliseconds but didn’t do anything.
![image](https://user-images.githubusercontent.com/109059089/178197492-df23840c-1e94-46f3-bb04-2afb991257cd.jpg)

https://user-images.githubusercontent.com/109059089/178197566-10bb51f1-694c-42bf-a1c9-4cc25a1ecc0c.MOV

![image](https://user-images.githubusercontent.com/109059089/178197708-5f830e0e-4abf-4b81-b5e2-da9edbd130f1.jpg)
![image](https://user-images.githubusercontent.com/109059089/178197731-b2b720c0-07eb-4885-aeff-8a65ebcedddb.jpg)
![image](https://user-images.githubusercontent.com/109059089/178198054-017ccd97-d34a-4d9a-b884-66472ee7ee14.jpg)

**Comment by kc9jud** [comment]
@Kbrown901 what fixed this for you? I'm seeing the same issue.

**Comment by Kbrown901** [comment]
> @Kbrown901 what fixed this for you? I'm seeing the same issue.

Only after I upgraded my server by repurposing my gaming rig which has a Nvidia GTX 1060 3G GPU in it did I get the opting to select video recognition, sad part is recognize says that there's an error for video recognition check logs, yet I have yet to find what exactly is the issue... one thing I have noticed is that when I leave the GUI (Ubuntu Minimum GUI) off the GPU gets turned off, so I wonder if I have to keep the GUI running for it to use it for the video recognition??? As of right now, I still have no idea what is wrong or how to fix it.

**Comment by marcelklehr** [comment]
Video recognition requires native libtensorflow execution and doesn't work in WASM mode, sadly.
