### ISSUE TITLE
Some tags are wonky

### ISSUE THREAD

**Issue by StarSmasher44** [marcelklehr/recognize#24]
Hi there, I have recently installed this app, and I am quite liking it so far and it seems to perform alright.

Although I did have a laugh when it classed all cats as dogs, and a ferret as a dog too.. Which brought me to the question; Is there any way to set up a setting to take a score of how good it assumes the classification is, and allow us to cut off whatever is "maybe a cat, maybe a dog, or maybe a ferret"? 

I believe it would help in the grand scheme of things, but my knowledge on how hard this would be to implement is limited.

**Comment by marcelklehr** [comment]
Hi, thanks for your feedback!

There is a list of thresholds for the different labels that can be adjusted: https://github.com/marcelklehr/recognize/blob/master/src/rules.yml

It's not quite straightforward, however, as the model makes much more distinctions than the actual labels of recognize.

**Comment by marcelklehr** [comment]
If you're up for a bit of testing you can run `occ recognize:classify` and examine the cli output to find a good threshold for dogs for example.

**Comment by marcelklehr** [comment]
With v1.4 I've significantly improved classification and cut out most false positives.

**Comment by StarSmasher44** [comment]
Awesome! Apologies for no longer responding, things got quite busy.

Im not sure if you'd like me to ask/put this in a seperate issue or you're fine with the heads-up, but I was under the impression recognize:classify would go through all of them, but it seems to be limited to the automated system's amounts (100 per time I run the command (I think? Can't verify), with 16000+ images that's a pain)
Not sure if intended or not, but perhaps a separate command to just force it to check all images it can find would be lovely!

Cheers!

**Comment by marcelklehr** [comment]
> I think? Can't verify

Mmh, you can check in the admin settings how many images have been processed so far, the command should go through as many as it can. Perhaps it only goes through them per user, though, I'll check that.

**Comment by nssatlantis** [comment]
I have chrcked, currently have 684 ish processed, ran the occ command around 5 to 6 times now. I'd expect it to go through them faster but it does seem like there is a limit of sorts

**Comment by Routhinator** [comment]
If we fix tags by changing them, does it learn? Right now for example it keeps identifying christmas presents as "basket" and babies as "bottle"
