### ISSUE TITLE
Error running out of memory

### ISSUE THREAD

**Issue by frznlogic** [marcelklehr/recognize#25]
Hi, 

I've been running into errors running out of memory, unfortunately I can't the complete message right now, but it seems that some images are causing a maxMemoryUsageInMB limit to be exceeded. 

Running this command:
`docker exec -it -u www-data docker.nextcloud.service ./occ recognize:classify`

And then I get this error:

```
RuntimeError: abort(Error: maxMemoryUsageInMB limit exceeded by at least 3MB). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:4685:9342)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

Using Recognize 1.3.1 with NextCloud 21.0.2

Currently no memory limits on the docker container it's running in, and I've got 5269MiB free memory and plenty of swap if necessary. 

Can I somehow bump the maxMemoryUsageInMB parameter somewhere, or is there some hack I can do for now to see if I can solve it? Not very used to working with php, node.js or tensorflow for that matter, but curious and really liking this so far;).

**Comment by marcelklehr** [comment]
It appears you are trying to classify images larger than 512MiB.

You can change this line to read https://github.com/marcelklehr/recognize/blob/master/src/classifier.js#L32

```
const imageData = jpeg.decode(imageBuffer, {useTArray: true, formatAsRGBA: false, maxMemoryUsageInMB: 1024})
```

It should now be able to read images up to 1GiB
