### ISSUE TITLE
no tag section in fotos

### ISSUE THREAD

**Issue by bendschs** [marcelklehr/recognize#32]
i was able to tag fotos via cli (automatic tagging did not work for some reason). now i see that i have 1400 fotos tagged in my settings page. however in the fotos site there is no section "tag".
whats wrong here?

**Comment by marcelklehr** [comment]
Which version of the photos app do you have installed?

**Comment by bendschs** [comment]
photos 1.3 on nextcloud 21.02

**Comment by marcelklehr** [comment]
Mh, I can't see why that would be. You'd have to ask over at https://github.com/nextcloud/photos, sorry.

**Comment by bendschs** [comment]
ok, could it be that it is shown only after tagging the entire library? that process is still running ...

**Comment by marcelklehr** [comment]
I don't think so. Tags are added directly to each file once it's processed, so as soon as one file is processed you should see some tags.

**Comment by bendschs** [comment]
turned out "collaborative tags" was not enabled.🤦‍♂️

**Comment by marcelklehr** [comment]
Ah, I will add that to the requirements.
