### ISSUE TITLE
Disk space quickly filling up with "core" files

### ISSUE THREAD

**Issue by liquidat** [marcelklehr/recognize#33]
[[issue template](https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md) is a dead link!]

I realized that the recognize app quickly eats away my disk space:

```
[root@host custom_apps]# du -sh recognize/
1.1T	recognize/
```

This seems to be largely due to "core" files in `recognize/lib/Service`:

```
[root@host Service]# du -sh .
1.1T	.
[root@host Service]# ls -lah core.9945 
-rw------- 1 33 33 2.6G Jul  6 17:58 core.9945
[root@host Service]# file core.9945
core.9945:           ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/var/www/html/custom_apps/recognize/bin/node-v14.9.0-linux-x64 /var/www/html/cu', real uid: 33, effective uid: 33, real gid: 33, effective gid: 33, execfn: '/var/www/html/custom_apps/recognize/bin/node-v14.9.0-linux-x64', platform: 'x86_64'

```

Any idea where this comes from?

**Comment by marcelklehr** [comment]
These are core dumps. Something seems to go haywire for you. You can check the nextcloud logs for more information.

**Comment by liquidat** [comment]
@marcelklehr Good to know - going through the logs nothing jump out to me. Any idea what I could look for?

**Comment by marcelklehr** [comment]
The recognize job only runs every 10minutes, if something happens to it, the log should have caught something. You could also try to run `php occ recognize:classify` manually to see what happens.
