### ISSUE TITLE
"Cannot be installed because appinfo file cannot be read"

### ISSUE THREAD

**Issue by davidcartwright** [marcelklehr/recognize#36]
Relevant error:

{"Exception":"Exception","Message":"App \"recognize\" cannot be installed because appinfo file cannot be read.","Code":0,"Trace":[{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->","args":["recognize"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["recognize"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/html/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Installer.php","Line":122,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.3.1","id":"60f9551e8386e"}

**Comment by marcelklehr** [comment]
I'll investigate this soon. Thanks for reporting!

**Comment by bonswouar** [comment]
It seems it could just be a timeout problem : https://help.nextcloud.com/t/cannot-install-documentserver-community-app-appinfo-file-cannot-be-read/68415/10
Although the proposed solution to manually edit a constant from a lib file isn't very appealing..

**Comment by marcelklehr** [comment]
It's likely a timeout problem. If you're on v22, try with the latest version. Otherwise, your only option currently is to install manually (download tar.gz file from this repo, unpack, chown and roll)

**Comment by bonswouar** [comment]
For your information there is an open issue on NC : https://github.com/nextcloud/server/issues/1899
Although it's only about informing the user that he should install the app manually
