### ISSUE TITLE
Recognize fails after the 6th image

### ISSUE THREAD

**Issue by KruyKaze** [marcelklehr/recognize#40]
Hello, I get this error when I try to run "occ recognize:classify" Error:

> Error: proc_open(): Exec failed: Argument list too long at /usr/share/webapps/nextcloud/3rdparty/symfony/process/Process.php#349{"reqId":"a1z6PBpN0d8UO4SkqKFR","level":3,"time":"2021-08-01T10:36:23+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"proc_open(): Exec failed: Argument list too long at /usr/share/webapps/nextcloud/3rdparty/symfony/process/Process.php#349","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/process/Process.php","line":349,"function":"proc_open"},{"file":"/usr/share/webapps/nextcloud/apps/recognize/lib/Service/ClassifyService.php","line":175,"function":"start","class":"Symfony\\Component\\Process\\Process","type":"->"},{"function":"OCA\\Recognize\\Service\\{closure}","class":"OCA\\Recognize\\Service\\ClassifyService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/apps/recognize/lib/Service/ClassifyService.php","line":181,"function":"array_walk"},{"file":"/usr/share/webapps/nextcloud/apps/recognize/lib/Command/Classify.php","line":102,"function":"classifyParallel","class":"OCA\\Recognize\\Service\\ClassifyService","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OCA\\Recognize\\Command\\Classify","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/occ","line":11,"args":["/usr/share/webapps/nextcloud/console.php"],"function":"require_once"}],"File":"/usr/share/webapps/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.3.1","id":"610679a3e83a6"}

I do have a lot of pictures and maybe Recognize gets overwhelmed. Is there a way to do a few pictures at a time maybe?

Thanks for looking into this.

Nextcloud 21
Arch linux 64bit
PHP 8.0.8

**Comment by marcelklehr** [comment]
Oh wow, we're hitting your system's ARG_MAX. :astonished: 
I'll release a patch for this shortly. In the mean time the background job will do 100 images at a time (which is much slower than what you could do with the command, but alas)

**Comment by KruyKaze** [comment]
Great. When will these be available on Nextcloud so I can test again?
Thanks
