### ISSUE TITLE
Skip not available external storages

### ISSUE THREAD

**Issue by jlaba** [marcelklehr/recognize#50]
Recognize seems to quit with Failed to classify images and no further notice (even with -vvv). In the owncloud log an error message "Exception":"OCP\\Files\\StorageNotAvailableException","Message":"Sabre\\HTTP\\ClientException: Failed to connect to [...] port 443: Connection refused","Code":1 [...] appears.

I hope the message relates to the recognize app (at least it come up with cat owncloud.log | grep recognize). If it is the case, not available external storages should be skipped.

If it is not the case, a hint how to debug the error is appreciated.

Regards!

**Comment by marcelklehr** [comment]
I would need the full log entry to know whether this is the relevant log entry. Please note, however, that I don't explicitly support Owncloud. If recognize works on owncloud, that's fine, but if it doesn't I can't help you.

**Comment by jlaba** [comment]
Please find the log entry below. We migrated to Nextcloud before installing the app. But we have not renamed te log file name, thats why I called it owncloud. Sorry for the confusion :-)

[log.txt](https://github.com/marcelklehr/recognize/files/6988570/log.txt)
