### ISSUE TITLE
Update not possible: Out-of-path file extraction

### ISSUE THREAD

**Issue by EmJotGeh** [marcelklehr/recognize#52]
recognize new version available: 1.5.1
recognize couldn't be updated

recognize new version available: 1.5.2
recognize couldn't be updated

Nextcloud 21.0.4

**Comment by MrLoverLoverMMMM** [comment]
yap exactly.
and if you try to reinstall you receive this error:
Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_T0cTMU-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}

**Comment by hdridder** [comment]
Same problem here: Message":"Could not extract app recognize: Out-of-path file extraction {/volume1/@tmp/oc_tmp_aYHmf1-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}

**Comment by marcelklehr** [comment]
Hi, sorry for your troubles and thank you for reporting! The new version seems to have some toothing problems. I'll investigate and release patches soon.

**Comment by marcelklehr** [comment]
Fixed in dec7e58

**Comment by MrLoverLoverMMMM** [comment]
When will you push it to the nextcloud store?
Their is still the old version avialable.

**Comment by marcelklehr** [comment]
New version is available now. Let me know if there are additional issues :hearts:

**Comment by hdridder** [comment]
Thanks. Upgrade from the GUI failed. On the commandline it reports:

```
# sudo -u http php74 /var/www/nextcloud/occ app:update recognize
Nextcloud is in maintenance mode - no apps have been loaded

recognize new version available: 1.5.3
/volume1/web/nextcloud/apps/recognize/bin/node-v14.17.4-linux-armv7l: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
recognize updated
```
Despite the error message recognize is now reported to be on version 1.5.3
The library reported in the error does exist on the filesystem
```
# ls -l /volume1/web/nextcloud/apps/recognize/bin/node-v14.17.4-linux-armv7l
-rwxr-xr-x 1 http http 67904012 Aug 20 20:06 /volume1/web/nextcloud/apps/recognize/bin/node-v14.17.4-linux-armv7l

```

**Comment by marcelklehr** [comment]
@hdridder Are you running on armv7l? The library reported missing is [libatomic.so.1](https://unix.stackexchange.com/questions/610119/how-to-resolve-libatomic-missing-error-or-more-generally-install-nodejs)

**Comment by hdridder** [comment]
Yes it is armv71 on a synology DS214÷

**Comment by marcelklehr** [comment]
It seems I cannot circumvent this bug, so I've reopened it here and over here: https://github.com/nextcloud/server/issues/26708

**Comment by spicemint** [comment]
I just tried to install the app on 21.0.4, raspbian:
`sudo -u www-data /usr/bin/php /var/www/nextcloud/occ app:install recognize
Error: Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_pofTyG-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}`

**Comment by DecaTec** [comment]
A manual update of the app seems to work.

**Comment by spicemint** [comment]
> A manual update of the app seems to work.

what other manual way is there besides what i tried? i also tried the webinterface, same issue

**Comment by DecaTec** [comment]
> what other manual way is there besides what i tried? i also tried the webinterface, same issue

Move the `recognize` folder out of the `apps` folder. Next, download the release archive from the release page and unpack it in the `apps` folder. Then `chown -R www-data:www-data /var/www/nextcloud/apps/recognize`.
After that, the upgrade is done in the browser.
