### ISSUE TITLE
DB errors when runnin 1.5.2

### ISSUE THREAD

**Issue by derritter88** [marcelklehr/recognize#55]
Hello @marcelklehr ,

thanks for enabling GPU support!
I have reinstalled the whole application and all the Nvidia stuff.

When running your app I get some DB errors in my Nextcloud log: `[index] Error: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535

GET /index.php/apps/recognize/admin/countMissed
from 192.168.10.2 by 3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3 at 2021-08-18T19:44:27+02:00`

DB backend: PostgresSQL 13
Nextcloud 22.1
OS: Ubuntu 20.04

**Comment by marcelklehr** [comment]
Hi, sorry for your troubles and thank you for reporting! The new version seems to have some toothing problems. I'll investigate and release patches soon.

**Comment by marcelklehr** [comment]
This will be fixed with the next release.

**Comment by derritter88** [comment]
Okay I see - any forecast when the new release will be launched?

**Comment by marcelklehr** [comment]
Here we go: https://github.com/marcelklehr/recognize/releases/tag/v1.5.4-beta.1

It's a pre-release, so it's not on the appstore, yet.
