### ISSUE TITLE
1.5.2 update error in snap install

### ISSUE THREAD

**Issue by ElectricPaperInformationssystemeGmbH** [marcelklehr/recognize#56]
Could not extract app recognize: Out-of-path file extraction {/var/snap/nextcloud/common/nextcloud/tmp/oc_tmp_st8jxN-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}

**Comment by gizmo84** [comment]
Same here! (local install without snap)

**Comment by brotkastn** [comment]
I am running Nextcloud 21.0.4 and am also unable to upgrade recognize from 1.4.2 to 1.5.2. 

The error is:

`Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_Y6ilJp-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0`

Install is a local install on Ubuntu 20.04 which has been migrated from owncloud.

Thank you for creating this addon!

**Comment by marcelklehr** [comment]
Hi, sorry for your troubles and thank you for reporting! The new version seems to have some toothing problems. I'll investigate and release patches soon.

**Comment by marcelklehr** [comment]
This will be fixed with the next release.
