### ISSUE TITLE
Error: file too short [1.5.3]

### ISSUE THREAD

**Issue by LotusAxt** [marcelklehr/recognize#57]
Hey there,
Thanks for the update, unfortunately I still get two errors when I run1.5.3.
I don't know whether this two errors are related or not.

> [recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: /var/www/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v8/../../deps/lib/libtensorflow_framework.so.2: file too short
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/var/www/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/index.js:60:16)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)

> [PHP] Error: file_get_contents(VALUE=uri:https://nextcloud.example.org/remote.php/dav/addressbooks/system/system/system/Database:Rafael.vcf?photo): failed to open stream: No such file or directory at /var/www/html/apps/recognize/lib/Service/ReferenceFacesFinderService.php#74

Please let me know if you need more information.

System:

> NC 22.1.0 (Debian Buster Docker image)
> DB: MariaDB 10
> Recognize: 1.5.3

**Comment by bonswouar** [comment]
Thanks for reporting, there seems to be some big issues coming from Contact images in latest release, it should be fixed soon!

**Comment by marcelklehr** [comment]
This particular error seems to be due to a bundling issue :/

**Comment by marcelklehr** [comment]
Here we go: https://github.com/marcelklehr/recognize/releases/tag/v1.5.4-beta.1

It's a pre-release, so it's not on the appstore, yet.
