### ISSUE TITLE
Error: More than 1000 expressions in a list are not allowed on Oracle.

### ISSUE THREAD

**Issue by LotusAxt** [marcelklehr/recognize#58]
Hey,

sorry, bit it looks like 1.5.3 didn't fix #53 for me. :( 

Still getting the error:

> [core] Error: More than 1000 expressions in a list are not allowed on Oracle.
> 
> GET /index.php/apps/recognize/admin/countMissed
> from 172.17.0.1 by Admin at 2021-08-20T14:40:04+00:00

**Comment by bonswouar** [comment]
I can confirm the issue is still here, same error on my end
