### ISSUE TITLE
1.5.3 App doesn't work after installation

### ISSUE THREAD

**Issue by Topchris18** [marcelklehr/recognize#59]
Hi @marcelklehr
tested the latest version 1.5.3.

After installation I waited 2h and then manually triggered the scan via occ recognize:classify.
It still didn't work and no tags are set for my pictures.
The log shows these Errors:
![Nextcloud Log](https://user-images.githubusercontent.com/49283837/130337094-7570c6cf-e07a-4295-b840-940a41f912d5.png)

**Comment by marcelklehr** [comment]
Hi @Topchris18

Are you using a glibc based linux distribution? Alpine linux for example is not such a distribution (see #16)

**Comment by Topchris18** [comment]
> Hi @Topchris18
> 
> Are you using a glibc based linux distribution? Alpine linux for example is not such a distribution (see #16)

I used this fix and it still didn't work.
So installed v1.5.4-beta.1 and everything worked like expected

**Comment by marcelklehr** [comment]
Nice!
