### ISSUE TITLE
Update / Install of Version 1.5.5 does not work on intel with ubuntu and apache 

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [marcelklehr/recognize#60]
Exception: Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_3Rz4q4-folder/recognize/node_modules/@tensorflow/tfjs-node/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}

    /var/www/nextcloud/lib/private/Installer.php - line 204:

    OC\Installer->downloadApp()

    /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 532:

    OC\Installer->updateAppstoreApp("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

**Comment by five2seven** [comment]
I know this was closed but I am having the same issue trying to update to 1.5.8 on Nextcloud 21.0.2

`Exception: Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_9e22GZ-folder/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow.so.2 --> libtensorflow.so.2.5.0}`

**Comment by marcelklehr** [comment]
Yep, I've reopened #52
