### ISSUE TITLE
Missing Module Error

### ISSUE THREAD

**Issue by LotusAxt** [marcelklehr/recognize#61]
Hey,
first of all thanks for your great work and the quick response over the last few days!
I really appreciate that.

But, it seems that there is a new error in 1.5.6 :( 

> [recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/var/www/html/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
>     at Module._compile (internal/modules/cjs/loader.js:1072:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 
> 
> at 2021-08-23T13:58:07+00:00

**Comment by jakobroehrl** [comment]
Get the same error with the 1.5.6:

Classifier process output: internal/modules/cjs/loader.js:1131 return process.dlopen(module, path.toNamespacedPath(filename)); ^ Error: libtensorflow.so.2: cannot open shared object file: No such file or directory at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18) at Module.load (internal/modules/cjs/loader.js:937:32) at Function.Module._load (internal/modules/cjs/loader.js:778:12) at Module.require (internal/modules/cjs/loader.js:961:19) at require (internal/modules/cjs/helpers.js:92:18) at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16) at Module._compile (internal/modules/cjs/loader.js:1072:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) at Module.load (internal/modules/cjs/loader.js:937:32) at Function.Module._load (internal/modules/cjs/loader.js:778:12)

**Comment by vanderheyde** [comment]
Same error on 1.5.5 updated via the nextcloud app store (#62)

```
[recognize] Warning: Classifier process output: internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libtensorflow.so.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

**Comment by marcelklehr** [comment]
Thanks for reporting and bearing with me! I feel like it's cursed. Whenever I fix one thing, something breaks again on the other end :D We'll have to improve CI at some point.

**Comment by marcelklehr** [comment]
v1.5.7 is out now :see_no_evil:

**Comment by jtrees** [comment]
I am running into this with v5.0.3 on NixOS. Let me know if I can provide you with more information for debugging.

**Comment by marcelklehr** [comment]
@jtrees please open a new issue
