### ISSUE TITLE
Add option to exclude folders?

### ISSUE THREAD

**Issue by ccgx** [marcelklehr/recognize#64]
Hi,

would it be possible to add the option to exclude certain folders? For example, I have my music collection in my cloud, but I dont need the albumart-jpgs in there classified.
Additionally we have a media folder mounted via external local storage for all users which doesnt need scanning either. Maybe here a option in the config file would be nice.

Thank you for your great app (:

**Comment by marcelklehr** [comment]
Hey, the app respects .nomedia and .noimage files. If you put one of those files in a folder, its contents won't be scanned by recognize :)

**Comment by bonswouar** [comment]
I'll just add that this  `.nomedia` feature is handled recursively (so fortunately, in your example, you can just add a `.noimage` file at the root of your music folder and/or external media folder)

**Comment by webartifex** [comment]
I observe that this does **not** work for external storages that are attached to one's cloud. I even put .nomedia files not only at the external storage's root but also into the sub-folders. This app simply ignores the .nomedia files.
However, for non-external folders, everything works as expected.

**Comment by marcelklehr** [comment]
@webartifex Could you open a new issue for this?
