### ISSUE TITLE
Feature Request: Alpine Linux Support

### ISSUE THREAD

**Issue by isaacolsen94** [marcelklehr/recognize#66]
I know a lot of people use the Unraid Nextcloud docker for their Nextcloud instance. Would it be possible to add native Alpine Linux support? 

A secondary thing to that is adding GPU support for alpine?

**Comment by marcelklehr** [comment]
I understand the problem. Unfortunately, I'd have to bundle pre-compiled versions of libtensorflow for Alpine for this, which I'm not sure if I want to.

If you want Alpine support *now*, however, you can always clone the repo and run `make all` (see [requirements](https://github.com/marcelklehr/recognize#dependencies)).

**Comment by marcelklehr** [comment]
It's now possible to set a path to a custom node.js binary. You can try if that already makes things work on Alpine.

**Comment by isaacolsen94** [comment]
I'll give this a go as well as the make all tomorrow. Thank you for looking into this!!

**Comment by kryst3q** [comment]
@isaacolsen94  How it went? Did you succeed? If yes could you describe in points what one has to do to make the app run on alpine?

**Comment by isaacolsen94** [comment]
> @isaacolsen94 How it went? Did you succeed? If yes could you describe in points what one has to do to make the app run on alpine?

I ended up giving up on the alpine install and creating an Ubuntu VM. There is a lot more support from that community.

**Comment by marcelklehr** [comment]
When changing the settings to use a custom node.js binary you should at least be able to run in JS-mode, which is considerably slower, but will get a performance boost next release thanks to WASM in node.js.

**Comment by marcelklehr** [comment]
Note to self and whomever it may concern: https://dev.to/ajeetraina/installing-nodejs-14-on-alpine-linux-154m

**Comment by marcelklehr** [comment]
Alpine support (even though not at full speed) will be in the next release.

**Comment by marcelklehr** [comment]
Say hello to [v1.11.0 musltoff](https://github.com/marcelklehr/recognize/releases/tag/v1.11.0)

**Comment by marcelklehr** [comment]
Please let me know if v1.11.0 works for you or if you run into #150 :pray:
