### ISSUE TITLE
Recognize faces

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/recognize#7]
https://github.com/justadudewhohacks/face-api.js

**Comment by ntimo** [comment]
There already is an app for that :) Maybe you would work together on a complete solution instead of building two different ones?

https://github.com/matiasdelellis/facerecognition

**Comment by marcelklehr** [comment]
@ntimo Ah, good point. Thanks for the heads up.

**Comment by jakobroehrl** [comment]
I would appreciate it if in this app could do the faces feature, because the https://github.com/matiasdelellis/facerecognition app is a little bit hard to configure

**Comment by marcelklehr** [comment]
I agree that their dependencies are quite cumbersome. But they have a good code base already apart from that, so there's no reason to reinvent the wheel. I've opened an issue :) https://github.com/matiasdelellis/facerecognition/issues/464

**Comment by Maulwurf16** [comment]
I really love this app - especially for its simplicity to set-up. Also, it works on web-spaces without terminal-access, as no extra dependencies have to be installed. Great work @marcelklehr 

As your issue at the other repo was closed, could you please re-open this one? I would love to see face-recognition in this app.

**Comment by marcelklehr** [comment]
@Maulwurf16 Thank you! This issue is still open :)
