### ISSUE TITLE
1.6.6: Failed to install Tensorflow.js

### ISSUE THREAD

**Issue by jakobroehrl** [marcelklehr/recognize#74]
![image](https://user-images.githubusercontent.com/24530680/131261548-ad999848-b2dc-4dba-bec0-323842ccfeb2.png)

**Comment by cloud2018** [comment]
still problem with install app 1.6.7 via command line with the following comands:
```
sudo -i
cd /var/www/nextcloud/apps/
wget https://github.com/marcelklehr/recognize/releases/download/v1.6.7/recognize-1.6.7.tar.gz
rm -r ./recognize/
tar xvzf recognize-1.6.7.tar.gz        
find ./recognize/ -type d -exec chmod 0750 {} \; 
find ./recognize/ -type f -exec chmod 0640 {} \;
chown -R www-data:www-data ./recognize
cd ..
sudo -u www-data php occ app:disable recognize
```
enable via command line:
```
sudo -u www-data php occ app:enable  recognize
Building TensorFlow Node.js bindings
Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
/bin/sh: 1: node-pre-gyp: Permission denied

```

enable via nextcloud GUI:
`Failed to install Tensorflow.js: CPU-linux-3.8.0.tar.gz node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build /bin/sh: 1: node-pre-gyp: Permission denied`

**Comment by marcelklehr** [comment]
@cloud2018 Please create a new issue if your error message doesn't match the contents of the issue you're about to comment on.

**Comment by marcelklehr** [comment]
`find ./recognize/ -type f -exec chmod 0640 {} \;` Change this to 0740 to allow execution, as there are some files that need to be executed.

**Comment by cloud2018** [comment]
thank you, now recognize is enabled :+1:

from [https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html?highlight=type](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html?highlight=type)  :
11. Adjust file ownership and permissions:
chown -R www-data:www-data nextcloud
find nextcloud/ -type d -exec chmod 750 {} \;
find nextcloud/ -type f -exec chmod 640 {} \;
