### ISSUE TITLE
[OOM] 1.6.10: Classifier process output:

### ISSUE THREAD

**Issue by jakobroehrl** [marcelklehr/recognize#75]
options;
![image](https://user-images.githubusercontent.com/24530680/131320164-4af857c6-9cbd-4a7d-9ea8-fa6ed607c178.png)

occ recognize:classify generates every time this error:
![image](https://user-images.githubusercontent.com/24530680/131320211-72246ddc-e59a-40ad-8cdd-a8219e4eef82.png)

**Comment by marcelklehr** [comment]
Mh. Can you increase log verbosity? Do you have multiple users on your instance? Do those users have photos for their contacts in the contacts app?

**Comment by jakobroehrl** [comment]
> Do you have multiple users on your instance? 
yes

> Do those users have photos for their contacts in the contacts app?
No, the contacts are not used

**Comment by marcelklehr** [comment]
> No, the contacts are not used

recognize uses users' contacts to recognize faces based on the photo of a contact, so recognize will not be of much use, if the contacts app is not used.

Still, it should not error in this case. I'll investigate.

**Comment by jakobroehrl** [comment]
It sill remains with the 1.6.9. 
More log lines are not printed on info level.

**Comment by marcelklehr** [comment]
Are you able to run the node.js binary shipped with recognize at `recognize/bin/node`?

**Comment by jakobroehrl** [comment]
> Are you able to run the node.js binary shipped with recognize at `recognize/bin/node`?

Hi, 
this
![image](https://user-images.githubusercontent.com/24530680/136163870-691b30a0-6c70-4b61-9944-c797368d770d.png)


leads to:
![image](https://user-images.githubusercontent.com/24530680/136163825-197a5a71-6936-4efe-88ed-9dfcd8df28c4.png)

Should I change a setting?

**Comment by marcelklehr** [comment]
Can you try running the node.js executable in your server shell to check if it works?

**Comment by jakobroehrl** [comment]
The contacts app is installed but most of the users don't use it

**Comment by marcelklehr** [comment]
Can you set the log level to debug?

**Comment by jakobroehrl** [comment]
These are the recognize log entries:

 * recognize	Running array ( 0 => '/var/www/nextcloud/apps/recognize/bin//node', 1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js', 2 => '-', )
 * recognize	Classifying array
 * Found a log photos
 * Searching files

**Comment by marcelklehr** [comment]
mmmh.

Can you try invoking the classifier directly to see what happens?

```
apps/recognize/bin/node apps/recognize/classifier_faces.js path/to/a/photo/with/a/face.jpg
```

**Comment by jakobroehrl** [comment]
There is no classifier_imagenet.js

root@server:/var/www/nextcloud/apps/recognize# ll /var/www/nextcloud/apps/recognize/classifier_imagenet.js
ls: cannot access '/var/www/nextcloud/apps/recognize/classifier_imagenet.js': No such file or directory

**Comment by marcelklehr** [comment]
Sorry, I updated the commands

**Comment by jakobroehrl** [comment]
classifier_imagenet
root@server:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_imagenet.js path/to/image/1.jpg
Illegal instruction (core dumped)

without image, the same:
root@server:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_imagenet.js 
Illegal instruction (core dumped)

classifier_faces:
root@server:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_faces.js path/to/image/2.jpg
Illegal instruction (core dumped)

**Comment by marcelklehr** [comment]
Mh, so there's still an instruction that is not supported.

Here's a build of libtensorflow for nehalem: https://github.com/marcelklehr/build_tensorflow/actions/runs/1404874146

The files in the archive should be placed at `apps/recognize/node_modules/@tensorflow/tfjs-node/deps/lib/`

**Comment by jakobroehrl** [comment]
OK, I will try it.
On another test system I get this:

root@localhost:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_imagenet.js /var/nc_data/root/files/Photos/Frog.jpg
2021-11-02 17:58:11.613858: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Error: Path /var/www/nextcloud/apps/recognize/model/model.json does not exist: loading failed
    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:67:23

**Comment by jakobroehrl** [comment]
> Here's a build of libtensorflow for nehalem: https://github.com/marcelklehr/build_tensorflow/actions/runs/1404874146
> 
> The files in the archive should be placed at `apps/recognize/node_modules/@tensorflow/tfjs-node/deps/lib/`

root@server:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_imagenet.js path/to/file/1.jpg
Killed

root@c:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_faces.js path/to/file/2.jpg
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at main (/var/www/nextcloud/apps/recognize/src/classifier_faces.js:45:31)

**Comment by marcelklehr** [comment]
> Killed?

Do you know why it was killed?

> SyntaxError: Unexpected end of JSON input

Ah, that's because classifier faces requires the reference pictures as json input, but we should be good testing with the imagenet classifier for now.

**Comment by jakobroehrl** [comment]
> Do you know why it was killed?

No idea, sorry. Tried it multiple times.

> > SyntaxError: Unexpected end of JSON input
> 
> Ah, that's because classifier faces requires the reference pictures as json input, but we should be good testing with the imagenet classifier for now.

What should I do now?

**Comment by marcelklehr** [comment]
> path/to/file/1.jpg

Did you replace this part in the command line with a path to an actual path to a picture?

> What should I do now?

The problem is that the process gets killed. It could be due to lack of memory, or something else. Perhaps you can run the command and observe how the metrics evolve in a task manager?

**Comment by jakobroehrl** [comment]
Maybe its a memory problem, if I execute it now:

root@server:/var/www/nextcloud# apps/recognize/bin/node apps/recognize/src/classifier_imagenet.js /var/nc_data/jakob/files/1.jpg
2021-11-07 13:06:06.028172: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 28753920 exceeds 10% of free system memory.
2021-11-07 13:06:06.228218: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 115015680 exceeds 10% of free system memory.
2021-11-07 13:06:06.468156: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 115015680 exceeds 10% of free system memory.
2021-11-07 13:06:07.678525: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 115015680 exceeds 10% of free system memory.
Killed


The VM has 4 GB Ram

**Comment by marcelklehr** [comment]
How large is that picture in MB?
