### ISSUE TITLE
Faces Finder : Group photos without Contact picture

### ISSUE THREAD

**Issue by bonswouar** [marcelklehr/recognize#76]
It'd be better to have ALL the faces pictures grouped, and then automatically be associated with Contacts pictures or manually by the user.
A very simple UI/UX would be needed, something similar to Google Photos for example https://www.wikihow.com/Label-Faces-in-Google-Photos

**Comment by jakobroehrl** [comment]
This is a great proposal. 
Maybe it would be useful to use tags for faces, too. 
Is there a way to see the faces on mobile devices?

**Comment by profzelonka** [comment]
How do you even see the photos recognized by your contact pic's face? Could really use some, any, info on the face recognition feature. This webpage is the most informative one on the feature.

**Comment by marcelklehr** [comment]
Currently, you set a face photo for your contacts and recognize will add a tag with the name of the contact to the photos in which their face appears.

**Comment by dantefff** [comment]
> Currently, you set a face photo for your contacts and recognize will add a tag with the name of the contact to the photos in which their face appears.

Please, can you explain this? Can it be done after initial scan? Or I must assign pictures to my contacts and then rescan all my pictures?

**Comment by marcelklehr** [comment]
@dantefff Indeed, that would be neat. For now, if you are admin, you could remove the tag 'Tagged by Recognize' for all files tagged with 'people', which will cause those to be rescanned.

**Comment by dantefff** [comment]
Nice to know. Thanks!
