### ISSUE TITLE
1.6.7: Failed to classify images

### ISSUE THREAD

**Issue by kaffeeringe** [marcelklehr/recognize#77]
Thank you for this great app! But I installed version 1.6.7 and when I run occ recognize:classify I get an error:
"Failed to classify images
Cannot decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."

What can I do?

**Comment by bonswouar** [comment]
@kaffeeringe it seems to be a problem with encrypted files, not sure how this is supposed to work. But looking at nextcloud's forums it looks like there are some issues : https://help.nextcloud.com/t/file-sharing-issue-with-server-side-encryption/9262

Is it working for some files still ? Are all your files encrypted ?
