### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by thelittlefireman** [marcelklehr/recognize#8]
Hi,
Thanks for this amazing project.

When i try to install it from application page i've got this error : 

```
Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_6ME6L3-folder/recognize/vendor/nodejs/nodejs/bin/npm --> ../lib/node_modules/npm/bin/npm-cli.js}
```

**Comment by marcelklehr** [comment]
Ah, this appears to be due to a [bug](https://github.com/nextcloud/server/issues/26708) in nextclou v21

I'll see what I can do

**Comment by marcelklehr** [comment]
Should be fixed now in v1.1.0

**Comment by marcelklehr** [comment]
v1.1.0 is still broken due to a different installation bug, but v1.2.0 should be installable via the app store now :sweat_smile:

**Comment by marcelklehr** [comment]
@thelittlefireman Let me know if v1.2.0 works for you (there's been another report for it already... https://github.com/marcelklehr/recognize/issues/10)

**Comment by thelittlefireman** [comment]
thanks for your quick fix and repy ! :) 

i try 1.2.0 but i've got an other issue : 

```
Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_IzL1Uf-folder/recognize/node_modules/.bin/tfjs-custom-module --> ../@tensorflow/tfjs/dist/tools/custom_module/cli.js}
```

**Comment by marcelklehr** [comment]
Yep, that's #10 :sweat_smile:

**Comment by thelittlefireman** [comment]
Ok that's working 👍 ! I succeed to install it, but how is it supposed to work ? I have no tags in the "tagged photos" menu

**Comment by Tamsy** [comment]
Another remark: When choosing Settings --> Recognize I just receive an empty page (FF 88.0) thus nothing there to configure  (v1.1.0 -> v1.2.1). Does this happen deliberately for the time being?

**Comment by marcelklehr** [comment]
> Does this happen deliberately for the time being?

Yep, that's deliberate.

**Comment by marcelklehr** [comment]
> I have no tags in the "tagged photos" menu.

Recognize works in the background. I'll scan your files for photos every 10mins. If something goes wrong it'll write data to the log.

**Comment by thelittlefireman** [comment]
> > I have no tags in the "tagged photos" menu.
> 
> Recognize works in the background. I'll scan your files for photos every 10mins. If something goes wrong it'll write data to the log.

Arf after 24h still nothing, and nothing in logs =/ any idea ?
