### ISSUE TITLE
Can't install any newer Nextcloud Version

### ISSUE THREAD

**Issue by debian-user-france1** [marcelklehr/recognize#85]
I don't know anymore what the error message is but it's like there is a file or folder missing (Nextcloud uses the tmp folder..)
I could install a new version manually (unzipping into apps folder etc.)

I might provide more information later
I have NC 21 (the newest stable version)
NC22 is still beta

**Comment by marcelklehr** [comment]
Is this a duplicate of #52 ?

**Comment by debian-user-france1** [comment]
#52

**Comment by debian-user-france1** [comment]
> Is this a duplicate of #52 ?

This issue is locked
Why?

**Comment by marcelklehr** [comment]
To prevent people from commenting. The issue is open, the cause is known. We'll have to wait for a fix. It doesn't help to have a comment from everyone who is affected.
