### ISSUE TITLE
Set a start directory.

### ISSUE THREAD

**Issue by tmsd2001** [marcelklehr/recognize#88]
It would be nice to be able to set a start directory.
At the moment, recognize working through directories that are actually no interest to me, 
I would like to skip them.

**Comment by bonswouar** [comment]
You can skip any directory adding a .noimage (or .nomedia) file in it, I think it should be enough for most use cases for now?
I've just added that to the documentation though as it's not obvious

**Comment by bonswouar** [comment]
> I think that should work.

Great !
> Can I later remove the file and the folder will be included again?

As far as I know it should work yes! (I haven't tested it though)

**Comment by tmsd2001** [comment]
I'll try it out
I have a .nomedia in all top folders, only not in one.
Let's see when the change takes effect.

**Comment by tmsd2001** [comment]
It seems Recognize doesn't start anymore when ".nomedia" is available.
I have tested it twice.
Where can I enable and see the debug log?

**Comment by bonswouar** [comment]
@tmsd2001 Did you "Reset tags for classified images" first?
At this point there is no special debug log I think, but you can still check nextcloud.log. What's the output when you run recognize command manually?

**Comment by tmsd2001** [comment]
No, I don't reset the TAGs.
I put the .nomedia file in a directory and wait, but recognize don't start.
If I start it manually it run a few seconds and end normal.
If I remove the .nomedia and run again, the recognize begin normal.

**Comment by bonswouar** [comment]
> I put the .nomedia file in a directory and wait, but recognize don't start.
> If I start it manually it run a few seconds and end normal.

Running it manually (Classify) or automatically (ClassifyJob) do basically the same thing, there shouldn't be any difference (except images slicing in the job).
What makes you think that recognize don't start ? There might be no log if there is no new image to classify though!

**Comment by tmsd2001** [comment]
I test it even with just one folder with .nomedia.
I think there is no distinction in which folder the file is located.
Does the file somewhere, Recognize stop.
I looked at the log file, but couldn't find anything, this surprises me, because there is also no start message.
I'll try what happens when the file is deeper in the folder

**Comment by tmsd2001** [comment]
Is this logfile from Recognize?
face_background_job.log

`
1/10 - Executing task CheckRequirementsTask (Check all requirements)
2/10 - Executing task CheckCronTask (Check that service is started from either cron or from command)
3/10 - Executing task LockTask (Acquire lock so that only one background task can run)
4/10 - Executing task DisabledUserRemovalTask (Purge all the information of a user when disable the analysis.)
5/10 - Executing task StaleImagesRemovalTask (Crawl for stale images (either missing in filesystem or under .nomedia) and remove them from DB)
	Removing stale image 1028861 for user thomasd
	Removing stale image 1028862 for user thomasd
	Removing stale image 1028863 for user thomasd
...
Time out. Quitting...
`

**Comment by tmsd2001** [comment]
As I can see, .nomedia and .noimage are a global file, so the system is unsuitable for only locking folders for recognize.
nomedia stop all action on this Folder, or do I think wrong?

**Comment by bonswouar** [comment]
@tmsd2001 I believe .nomedia convention is also used by Nextcloud Photos, and probably some other media plugin. So yes it's not only for Recognize, but it doesn't prevent "normal" actions (anything not "media related" basically)
