### ISSUE TITLE
pictures randomly disappear (many cat-pictures aren't tagged anymore)

### ISSUE THREAD

**Issue by debian-user-france1** [marcelklehr/recognize#91]
_no description... why does this happen?_

**Comment by marcelklehr** [comment]
> pictures randomly disappear

What does this mean? Files are deleted?

**Comment by debian-user-france1** [comment]
The files lose the tags (I can't see many of my cat-pictures that where tagged once)

I am pretty sure that they still exist

**Comment by marcelklehr** [comment]
If you clicked on reset in the admin settings then you'll have to wait until they are re-classified. Recognize doesn't remove tags otherwise. Cats should still be rather well recognized (`true positive rate: 0.93, true negative rate: 0.83`)

**Comment by debian-user-france1** [comment]
No I didn't reset it. Just re-run the manual classifier

**Comment by bonswouar** [comment]
> I can't see many of my cat-pictures that where tagged once

Was "once" a long time ago? Because model has been changed few times (even if newer model is better it's not impossible an older one had more positives for some keywords)

Although I second @marcelklehr , I don't see any way Recognize would reset tags without clicking on it in the setting... :thinking:

**Comment by debian-user-france1** [comment]
Maybe the tagging program is doing it 

Could that be possible?

**Comment by marcelklehr** [comment]
I think it's most likely that an old version of recognize may have added those tags, but after updating and resetting the tags, the newer version no longer recognizes those specific pictures and doesn't add those tags anymore. Closing for now. Feel free to shout here, if you encounter this again.
