### ISSUE TITLE
Failed to classify images: Permission denied

### ISSUE THREAD

**Issue by feyded1020** [marcelklehr/recognize#96]
I am trying to run the recognize app on my unraid NC docker install(22.1.0), but when I try to run the app either automatically or manually through terminal. I am greeted by:

```
root@5acf1b785cfe:/# sudo occ recognize:classify
Classifying photos of user Feyded
Failed to classify images
Classifier process error
```

When I check my NC logs, I see that it says the code below even if run with sudo occ recognize:classify
```
[recognize] Warning: Classifier process output: sh: exec: line 1: : Permission denied
at 2021-10-03T01:41:59+00:00
```

Please help, Im unsure of where to go from here.

**Comment by yrangana** [comment]
I'm also having this issue.. 
running NC on docker

**Comment by bonswouar** [comment]
Not sure how unraid works, but are you executing your docker shell with the same user as your webserver's user?

**Comment by marcelklehr** [comment]
This may be a reincarnation of https://github.com/marcelklehr/recognize/issues/16

**Comment by borderland-it** [comment]
root@086fc2f0005a:/# ldd --version
musl libc (x86_64)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname

**Comment by marcelklehr** [comment]
You can also install node.js for Alpine and set the path to the binary in the recognize settings.

**Comment by borderland-it** [comment]
and if i now reinstall this app, i will get this error. 
abc@086fc2f0005a:/config/www/nextcloud/apps$ php /config/www/nextcloud/console.php app:install recognize --keep-disabled
/config/www/nextcloud/apps/recognize/bin//node: line 1: ELFHl@@8: not found
/config/www/nextcloud/apps/recognize/bin//node: line 2: syntax error: unexpected ")"
/config/www/nextcloud/apps/recognize/bin//node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

**Comment by bonswouar** [comment]
@borderland-it https://wiki.alpinelinux.org/wiki/Running_glibc_programs
You might have to uninstall musl libc first though

**Comment by ColonelSanderson** [comment]
I'm having the same issue with linuxserver's docker container, NC22, node 14.17.6  and libc 1.2.2

**Comment by ColonelSanderson** [comment]
I'm still having this issue with NC22 on linuxserver's docker container :(

**Comment by marcelklehr** [comment]
@ColonelSanderson Make sure glibc is installed and you can run glibc programs, e.g. the node binary in recognize/bin/node.
